// Copyright 2026 libsignal-go contributors.
// SPDX-License-Identifier: AGPL-3.0-only
//
// The SPQR slice-completion oracle: a lockstep send/recv exchange driven against
// the spqr crate's own committed regression fixtures, ported from lib.rs
// regression_test_libcrux_issue_1275_from_generated_states.

package spqr

import (
	"bytes"
	"crypto/rand"
	"testing"
)

// TestIssue1275Regression mirrors lib.rs
// regression_test_libcrux_issue_1275_from_generated_states. The two fixtures are
// real PqRatchetState bytes generated by the spqr crate 30 steps into a lockstep
// protocol, using the OLD libcrux "portable" EncapsState serialization (prior to
// the issue-1275/PR-1276 endianness fix). The send_ct side has stored an
// EncapsState locally but has not yet called Encapsulate2 on it.
//
// Driving 20 more lockstep steps (30->50) forces that side to Encapsulate2 the
// stored, wrong-endianness es. Each step must still produce matching A/B message
// keys and reach epoch 2 successfully — which it can only do if Encapsulate2
// detects and corrects the swapped es bytes internally
// (mlkem768incr.Encapsulate2's embedded issue-1275 fix). If the bad state were
// mishandled, a step would fail (KEM decapsulation mismatch -> MAC failure ->
// error) or the keys would diverge.
//
// This is the SPQR Slice C completion gate: a full bidirectional conversation
// continued from crate-generated state, exercising the KEM (incremental
// ML-KEM-768 + the 1275 fix), the chunked transport, the authenticator, the
// epoch Chain, and the message codec end to end against the reference's own
// vectors.
func TestIssue1275Regression(t *testing.T) {
	alex := readFixture(t, "issue1275_a_state.in")
	blake := readFixture(t, "issue1275_b_state.in")

	for i := 30; i < 50; i++ {
		// A -> B
		sr, err := Send(alex, rand.Reader)
		if err != nil {
			t.Fatalf("step %d alex send: %v", i, err)
		}
		alex = sr.State
		rr, err := Recv(blake, sr.Msg)
		if err != nil {
			t.Fatalf("step %d blake recv: %v", i, err)
		}
		blake = rr.State
		if !bytes.Equal(sr.Key, rr.Key) {
			t.Fatalf("step %d A->B key mismatch: %x vs %x", i, sr.Key, rr.Key)
		}

		// B -> A
		sr, err = Send(blake, rand.Reader)
		if err != nil {
			t.Fatalf("step %d blake send: %v", i, err)
		}
		blake = sr.State
		rr, err = Recv(alex, sr.Msg)
		if err != nil {
			t.Fatalf("step %d alex recv: %v", i, err)
		}
		alex = rr.State
		if !bytes.Equal(sr.Key, rr.Key) {
			t.Fatalf("step %d B->A key mismatch: %x vs %x", i, sr.Key, rr.Key)
		}
	}

	// After 20 steps both sides should have advanced past the fixture's epoch.
	na, err := Negotiation(alex)
	if err != nil {
		t.Fatal(err)
	}
	nb, err := Negotiation(blake)
	if err != nil {
		t.Fatal(err)
	}
	if na.Negotiating || nb.Negotiating {
		t.Fatalf("negotiation should be complete after the conversation: a=%+v b=%+v", na, nb)
	}
}
