package groups

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// TestSenderKeyDerivationKAT pins the sender-key primitives byte-for-byte
// against the upstream-generated vectors in compat/vectors/groups.json
// (`derivations` array), the same way ratchet/ is pinned against hkdf.json. T20's
// in-package tests only asserted the message-key derivation's length and
// determinism; this asserts the actual output bytes match upstream libsignal
// v0.91.0:
//
//   - SenderChainKey.next().Seed() == HMAC-SHA256(chain_key, [0x02])
//   - the senderMessageKey iv/cipherKey == HKDF-SHA256(
//     HMAC-SHA256(chain_key, [0x01]), salt=None, "WhisperGroup")[0:16] / [16:48]
//
// It is a white-box test (package groups) because the chain-key ratchet step and
// senderMessageKey derivation are unexported; the consumer reads the committed
// vector file directly via a relative path.
func TestSenderKeyDerivationKAT(t *testing.T) {
	var batch struct {
		Derivations []struct {
			Iteration      uint32 `json:"iteration"`
			ChainKey       string `json:"chain_key"`
			NextChainKey   string `json:"next_chain_key"`
			MessageKeySeed string `json:"message_key_seed"`
			IV             string `json:"iv"`
			CipherKey      string `json:"cipher_key"`
		} `json:"derivations"`
	}
	// The vectors live under compat/, generated by the Rust harness and committed
	// (no Rust toolchain needed here). Path is relative to this test's package dir.
	path := filepath.Join("..", "compat", "vectors", "groups.json")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	if err := json.Unmarshal(data, &batch); err != nil {
		t.Fatalf("decode %s: %v", path, err)
	}
	if len(batch.Derivations) == 0 {
		t.Fatal("groups.json: no derivation KAT cases (expected a `derivations` array)")
	}

	for i, c := range batch.Derivations {
		chainKey := mustHexKAT(t, c.ChainKey)
		ck := newSenderChainKey(c.Iteration, chainKey)

		// Chain-key ratchet step: next seed must equal upstream's HMAC output.
		next, err := ck.next()
		if err != nil {
			t.Fatalf("case %d: next: %v", i, err)
		}
		if want := mustHexKAT(t, c.NextChainKey); !bytes.Equal(next.Seed(), want) {
			t.Fatalf("case %d: next chain key\n got  %x\n want %x", i, next.Seed(), want)
		}
		if next.Iteration() != c.Iteration+1 {
			t.Fatalf("case %d: next iteration = %d, want %d", i, next.Iteration(), c.Iteration+1)
		}

		// Message-key derivation: iv and cipher key must equal upstream's HKDF
		// output (info "WhisperGroup"), and the message key must carry the chain's
		// iteration.
		mk, err := ck.senderMessageKey()
		if err != nil {
			t.Fatalf("case %d: senderMessageKey: %v", i, err)
		}
		if mk.Iteration() != c.Iteration {
			t.Fatalf("case %d: message key iteration = %d, want %d", i, mk.Iteration(), c.Iteration)
		}
		if want := mustHexKAT(t, c.IV); !bytes.Equal(mk.IV(), want) {
			t.Fatalf("case %d: message key iv\n got  %x\n want %x", i, mk.IV(), want)
		}
		if want := mustHexKAT(t, c.CipherKey); !bytes.Equal(mk.CipherKey(), want) {
			t.Fatalf("case %d: message key cipher key\n got  %x\n want %x", i, mk.CipherKey(), want)
		}
	}
	t.Logf("sender-key derivation KAT: %d cases pinned byte-exact vs upstream", len(batch.Derivations))
}

func mustHexKAT(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("bad hex %q: %v", s, err)
	}
	return b
}
