// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: fingerprint.proto

//
// Copyright 2020 Signal Messenger, LLC.
// SPDX-License-Identifier: AGPL-3.0-only
//

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogicalFingerprint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"` // bytes identifier = 2;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogicalFingerprint) Reset() {
	*x = LogicalFingerprint{}
	mi := &file_fingerprint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalFingerprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalFingerprint) ProtoMessage() {}

func (x *LogicalFingerprint) ProtoReflect() protoreflect.Message {
	mi := &file_fingerprint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalFingerprint.ProtoReflect.Descriptor instead.
func (*LogicalFingerprint) Descriptor() ([]byte, []int) {
	return file_fingerprint_proto_rawDescGZIP(), []int{0}
}

func (x *LogicalFingerprint) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type CombinedFingerprints struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Version           *uint32                `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	LocalFingerprint  *LogicalFingerprint    `protobuf:"bytes,2,opt,name=local_fingerprint,json=localFingerprint" json:"local_fingerprint,omitempty"`
	RemoteFingerprint *LogicalFingerprint    `protobuf:"bytes,3,opt,name=remote_fingerprint,json=remoteFingerprint" json:"remote_fingerprint,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CombinedFingerprints) Reset() {
	*x = CombinedFingerprints{}
	mi := &file_fingerprint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombinedFingerprints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombinedFingerprints) ProtoMessage() {}

func (x *CombinedFingerprints) ProtoReflect() protoreflect.Message {
	mi := &file_fingerprint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombinedFingerprints.ProtoReflect.Descriptor instead.
func (*CombinedFingerprints) Descriptor() ([]byte, []int) {
	return file_fingerprint_proto_rawDescGZIP(), []int{1}
}

func (x *CombinedFingerprints) GetVersion() uint32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *CombinedFingerprints) GetLocalFingerprint() *LogicalFingerprint {
	if x != nil {
		return x.LocalFingerprint
	}
	return nil
}

func (x *CombinedFingerprints) GetRemoteFingerprint() *LogicalFingerprint {
	if x != nil {
		return x.RemoteFingerprint
	}
	return nil
}

var File_fingerprint_proto protoreflect.FileDescriptor

const file_fingerprint_proto_rawDesc = "" +
	"\n" +
	"\x11fingerprint.proto\x12\x18signal.proto.fingerprint\".\n" +
	"\x12LogicalFingerprint\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"\xe8\x01\n" +
	"\x14CombinedFingerprints\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12Y\n" +
	"\x11local_fingerprint\x18\x02 \x01(\v2,.signal.proto.fingerprint.LogicalFingerprintR\x10localFingerprint\x12[\n" +
	"\x12remote_fingerprint\x18\x03 \x01(\v2,.signal.proto.fingerprint.LogicalFingerprintR\x11remoteFingerprintB+Z)github.com/GoCodeAlone/libsignal-go/proto"

var (
	file_fingerprint_proto_rawDescOnce sync.Once
	file_fingerprint_proto_rawDescData []byte
)

func file_fingerprint_proto_rawDescGZIP() []byte {
	file_fingerprint_proto_rawDescOnce.Do(func() {
		file_fingerprint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fingerprint_proto_rawDesc), len(file_fingerprint_proto_rawDesc)))
	})
	return file_fingerprint_proto_rawDescData
}

var file_fingerprint_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fingerprint_proto_goTypes = []any{
	(*LogicalFingerprint)(nil),   // 0: signal.proto.fingerprint.LogicalFingerprint
	(*CombinedFingerprints)(nil), // 1: signal.proto.fingerprint.CombinedFingerprints
}
var file_fingerprint_proto_depIdxs = []int32{
	0, // 0: signal.proto.fingerprint.CombinedFingerprints.local_fingerprint:type_name -> signal.proto.fingerprint.LogicalFingerprint
	0, // 1: signal.proto.fingerprint.CombinedFingerprints.remote_fingerprint:type_name -> signal.proto.fingerprint.LogicalFingerprint
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_fingerprint_proto_init() }
func file_fingerprint_proto_init() {
	if File_fingerprint_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fingerprint_proto_rawDesc), len(file_fingerprint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fingerprint_proto_goTypes,
		DependencyIndexes: file_fingerprint_proto_depIdxs,
		MessageInfos:      file_fingerprint_proto_msgTypes,
	}.Build()
	File_fingerprint_proto = out.File
	file_fingerprint_proto_goTypes = nil
	file_fingerprint_proto_depIdxs = nil
}
