// Copyright 2025 Signal Messenger, LLC.
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pq_ratchet.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Version int32

const (
	Version_V_0 Version = 0 // disabled
	Version_V_1 Version = 1
)

// Enum value maps for Version.
var (
	Version_name = map[int32]string{
		0: "V_0",
		1: "V_1",
	}
	Version_value = map[string]int32{
		"V_0": 0,
		"V_1": 1,
	}
)

func (x Version) Enum() *Version {
	p := new(Version)
	*p = x
	return p
}

func (x Version) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Version) Descriptor() protoreflect.EnumDescriptor {
	return file_pq_ratchet_proto_enumTypes[0].Descriptor()
}

func (Version) Type() protoreflect.EnumType {
	return &file_pq_ratchet_proto_enumTypes[0]
}

func (x Version) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Version.Descriptor instead.
func (Version) EnumDescriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{0}
}

type Direction int32

const (
	Direction_A_2_B Direction = 0
	Direction_B_2_A Direction = 1
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "A_2_B",
		1: "B_2_A",
	}
	Direction_value = map[string]int32{
		"A_2_B": 0,
		"B_2_A": 1,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_pq_ratchet_proto_enumTypes[1].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_pq_ratchet_proto_enumTypes[1]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{1}
}

type PolynomialEncoder struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Idx   uint32                 `protobuf:"varint,1,opt,name=idx,proto3" json:"idx,omitempty"`
	// We'd like to use a oneof here, but proto3 doesn't allow
	// a combination of `oneof` and `repeated`.  So, we just
	// only set one of these values to non-empty:
	Pts           [][]byte `protobuf:"bytes,2,rep,name=pts,proto3" json:"pts,omitempty"`
	Polys         [][]byte `protobuf:"bytes,3,rep,name=polys,proto3" json:"polys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolynomialEncoder) Reset() {
	*x = PolynomialEncoder{}
	mi := &file_pq_ratchet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolynomialEncoder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolynomialEncoder) ProtoMessage() {}

func (x *PolynomialEncoder) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolynomialEncoder.ProtoReflect.Descriptor instead.
func (*PolynomialEncoder) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{0}
}

func (x *PolynomialEncoder) GetIdx() uint32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *PolynomialEncoder) GetPts() [][]byte {
	if x != nil {
		return x.Pts
	}
	return nil
}

func (x *PolynomialEncoder) GetPolys() [][]byte {
	if x != nil {
		return x.Polys
	}
	return nil
}

type PolynomialDecoder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PtsNeeded     uint32                 `protobuf:"varint,1,opt,name=pts_needed,json=ptsNeeded,proto3" json:"pts_needed,omitempty"`
	Polys         uint32                 `protobuf:"varint,2,opt,name=polys,proto3" json:"polys,omitempty"`
	Pts           [][]byte               `protobuf:"bytes,3,rep,name=pts,proto3" json:"pts,omitempty"`
	IsComplete    bool                   `protobuf:"varint,4,opt,name=is_complete,json=isComplete,proto3" json:"is_complete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolynomialDecoder) Reset() {
	*x = PolynomialDecoder{}
	mi := &file_pq_ratchet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolynomialDecoder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolynomialDecoder) ProtoMessage() {}

func (x *PolynomialDecoder) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolynomialDecoder.ProtoReflect.Descriptor instead.
func (*PolynomialDecoder) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{1}
}

func (x *PolynomialDecoder) GetPtsNeeded() uint32 {
	if x != nil {
		return x.PtsNeeded
	}
	return 0
}

func (x *PolynomialDecoder) GetPolys() uint32 {
	if x != nil {
		return x.Polys
	}
	return 0
}

func (x *PolynomialDecoder) GetPts() [][]byte {
	if x != nil {
		return x.Pts
	}
	return nil
}

func (x *PolynomialDecoder) GetIsComplete() bool {
	if x != nil {
		return x.IsComplete
	}
	return false
}

type PqRatchetState struct {
	state              protoimpl.MessageState             `protogen:"open.v1"`
	VersionNegotiation *PqRatchetState_VersionNegotiation `protobuf:"bytes,1,opt,name=version_negotiation,json=versionNegotiation,proto3" json:"version_negotiation,omitempty"`
	Chain              *Chain                             `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	// Types that are valid to be assigned to Inner:
	//
	//	*PqRatchetState_V1
	Inner         isPqRatchetState_Inner `protobuf_oneof:"inner"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PqRatchetState) Reset() {
	*x = PqRatchetState{}
	mi := &file_pq_ratchet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PqRatchetState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PqRatchetState) ProtoMessage() {}

func (x *PqRatchetState) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PqRatchetState.ProtoReflect.Descriptor instead.
func (*PqRatchetState) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{2}
}

func (x *PqRatchetState) GetVersionNegotiation() *PqRatchetState_VersionNegotiation {
	if x != nil {
		return x.VersionNegotiation
	}
	return nil
}

func (x *PqRatchetState) GetChain() *Chain {
	if x != nil {
		return x.Chain
	}
	return nil
}

func (x *PqRatchetState) GetInner() isPqRatchetState_Inner {
	if x != nil {
		return x.Inner
	}
	return nil
}

func (x *PqRatchetState) GetV1() *V1State {
	if x != nil {
		if x, ok := x.Inner.(*PqRatchetState_V1); ok {
			return x.V1
		}
	}
	return nil
}

type isPqRatchetState_Inner interface {
	isPqRatchetState_Inner()
}

type PqRatchetState_V1 struct {
	V1 *V1State `protobuf:"bytes,3,opt,name=v1,proto3,oneof"`
}

func (*PqRatchetState_V1) isPqRatchetState_Inner() {}

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_pq_ratchet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{3}
}

func (x *Chunk) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Chunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type V1Msg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Epoch uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Index uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// Types that are valid to be assigned to InnerMsg:
	//
	//	*V1Msg_Hdr
	//	*V1Msg_Ek
	//	*V1Msg_EkCt1Ack
	//	*V1Msg_Ct1Ack
	//	*V1Msg_Ct1
	//	*V1Msg_Ct2
	InnerMsg      isV1Msg_InnerMsg `protobuf_oneof:"inner_msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1Msg) Reset() {
	*x = V1Msg{}
	mi := &file_pq_ratchet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1Msg) ProtoMessage() {}

func (x *V1Msg) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1Msg.ProtoReflect.Descriptor instead.
func (*V1Msg) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{4}
}

func (x *V1Msg) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *V1Msg) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *V1Msg) GetInnerMsg() isV1Msg_InnerMsg {
	if x != nil {
		return x.InnerMsg
	}
	return nil
}

func (x *V1Msg) GetHdr() *Chunk {
	if x != nil {
		if x, ok := x.InnerMsg.(*V1Msg_Hdr); ok {
			return x.Hdr
		}
	}
	return nil
}

func (x *V1Msg) GetEk() *Chunk {
	if x != nil {
		if x, ok := x.InnerMsg.(*V1Msg_Ek); ok {
			return x.Ek
		}
	}
	return nil
}

func (x *V1Msg) GetEkCt1Ack() *Chunk {
	if x != nil {
		if x, ok := x.InnerMsg.(*V1Msg_EkCt1Ack); ok {
			return x.EkCt1Ack
		}
	}
	return nil
}

func (x *V1Msg) GetCt1Ack() bool {
	if x != nil {
		if x, ok := x.InnerMsg.(*V1Msg_Ct1Ack); ok {
			return x.Ct1Ack
		}
	}
	return false
}

func (x *V1Msg) GetCt1() *Chunk {
	if x != nil {
		if x, ok := x.InnerMsg.(*V1Msg_Ct1); ok {
			return x.Ct1
		}
	}
	return nil
}

func (x *V1Msg) GetCt2() *Chunk {
	if x != nil {
		if x, ok := x.InnerMsg.(*V1Msg_Ct2); ok {
			return x.Ct2
		}
	}
	return nil
}

type isV1Msg_InnerMsg interface {
	isV1Msg_InnerMsg()
}

type V1Msg_Hdr struct {
	// send_ek
	Hdr *Chunk `protobuf:"bytes,3,opt,name=hdr,proto3,oneof"`
}

type V1Msg_Ek struct {
	Ek *Chunk `protobuf:"bytes,4,opt,name=ek,proto3,oneof"`
}

type V1Msg_EkCt1Ack struct {
	EkCt1Ack *Chunk `protobuf:"bytes,5,opt,name=ek_ct1_ack,json=ekCt1Ack,proto3,oneof"`
}

type V1Msg_Ct1Ack struct {
	Ct1Ack bool `protobuf:"varint,6,opt,name=ct1_ack,json=ct1Ack,proto3,oneof"`
}

type V1Msg_Ct1 struct {
	// send_ct
	Ct1 *Chunk `protobuf:"bytes,7,opt,name=ct1,proto3,oneof"`
}

type V1Msg_Ct2 struct {
	Ct2 *Chunk `protobuf:"bytes,8,opt,name=ct2,proto3,oneof"`
}

func (*V1Msg_Hdr) isV1Msg_InnerMsg() {}

func (*V1Msg_Ek) isV1Msg_InnerMsg() {}

func (*V1Msg_EkCt1Ack) isV1Msg_InnerMsg() {}

func (*V1Msg_Ct1Ack) isV1Msg_InnerMsg() {}

func (*V1Msg_Ct1) isV1Msg_InnerMsg() {}

func (*V1Msg_Ct2) isV1Msg_InnerMsg() {}

type Authenticator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootKey       []byte                 `protobuf:"bytes,1,opt,name=root_key,json=rootKey,proto3" json:"root_key,omitempty"`
	MacKey        []byte                 `protobuf:"bytes,2,opt,name=mac_key,json=macKey,proto3" json:"mac_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authenticator) Reset() {
	*x = Authenticator{}
	mi := &file_pq_ratchet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authenticator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authenticator) ProtoMessage() {}

func (x *Authenticator) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authenticator.ProtoReflect.Descriptor instead.
func (*Authenticator) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{5}
}

func (x *Authenticator) GetRootKey() []byte {
	if x != nil {
		return x.RootKey
	}
	return nil
}

func (x *Authenticator) GetMacKey() []byte {
	if x != nil {
		return x.MacKey
	}
	return nil
}

type V1State struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to InnerState:
	//
	//	*V1State_KeysUnsampled
	//	*V1State_KeysSampled
	//	*V1State_HeaderSent
	//	*V1State_Ct1Received
	//	*V1State_EkSentCt1Received
	//	*V1State_NoHeaderReceived
	//	*V1State_HeaderReceived
	//	*V1State_Ct1Sampled
	//	*V1State_EkReceivedCt1Sampled
	//	*V1State_Ct1Acknowledged
	//	*V1State_Ct2Sampled
	InnerState    isV1State_InnerState `protobuf_oneof:"inner_state"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1State) Reset() {
	*x = V1State{}
	mi := &file_pq_ratchet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1State) ProtoMessage() {}

func (x *V1State) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1State.ProtoReflect.Descriptor instead.
func (*V1State) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{6}
}

func (x *V1State) GetInnerState() isV1State_InnerState {
	if x != nil {
		return x.InnerState
	}
	return nil
}

func (x *V1State) GetKeysUnsampled() *V1State_Chunked_KeysUnsampled {
	if x != nil {
		if x, ok := x.InnerState.(*V1State_KeysUnsampled); ok {
			return x.KeysUnsampled
		}
	}
	return nil
}

func (x *V1State) GetKeysSampled() *V1State_Chunked_KeysSampled {
	if x != nil {
		if x, ok := x.InnerState.(*V1State_KeysSampled); ok {
			return x.KeysSampled
		}
	}
	return nil
}

func (x *V1State) GetHeaderSent() *V1State_Chunked_HeaderSent {
	if x != nil {
		if x, ok := x.InnerState.(*V1State_HeaderSent); ok {
			return x.HeaderSent
		}
	}
	return nil
}

func (x *V1State) GetCt1Received() *V1State_Chunked_Ct1Received {
	if x != nil {
		if x, ok := x.InnerState.(*V1State_Ct1Received); ok {
			return x.Ct1Received
		}
	}
	return nil
}

func (x *V1State) GetEkSentCt1Received() *V1State_Chunked_EkSentCt1Received {
	if x != nil {
		if x, ok := x.InnerState.(*V1State_EkSentCt1Received); ok {
			return x.EkSentCt1Received
		}
	}
	return nil
}

func (x *V1State) GetNoHeaderReceived() *V1State_Chunked_NoHeaderReceived {
	if x != nil {
		if x, ok := x.InnerState.(*V1State_NoHeaderReceived); ok {
			return x.NoHeaderReceived
		}
	}
	return nil
}

func (x *V1State) GetHeaderReceived() *V1State_Chunked_HeaderReceived {
	if x != nil {
		if x, ok := x.InnerState.(*V1State_HeaderReceived); ok {
			return x.HeaderReceived
		}
	}
	return nil
}

func (x *V1State) GetCt1Sampled() *V1State_Chunked_Ct1Sampled {
	if x != nil {
		if x, ok := x.InnerState.(*V1State_Ct1Sampled); ok {
			return x.Ct1Sampled
		}
	}
	return nil
}

func (x *V1State) GetEkReceivedCt1Sampled() *V1State_Chunked_EkReceivedCt1Sampled {
	if x != nil {
		if x, ok := x.InnerState.(*V1State_EkReceivedCt1Sampled); ok {
			return x.EkReceivedCt1Sampled
		}
	}
	return nil
}

func (x *V1State) GetCt1Acknowledged() *V1State_Chunked_Ct1Acknowledged {
	if x != nil {
		if x, ok := x.InnerState.(*V1State_Ct1Acknowledged); ok {
			return x.Ct1Acknowledged
		}
	}
	return nil
}

func (x *V1State) GetCt2Sampled() *V1State_Chunked_Ct2Sampled {
	if x != nil {
		if x, ok := x.InnerState.(*V1State_Ct2Sampled); ok {
			return x.Ct2Sampled
		}
	}
	return nil
}

type isV1State_InnerState interface {
	isV1State_InnerState()
}

type V1State_KeysUnsampled struct {
	// // send_ek ////
	KeysUnsampled *V1State_Chunked_KeysUnsampled `protobuf:"bytes,1,opt,name=keys_unsampled,json=keysUnsampled,proto3,oneof"`
}

type V1State_KeysSampled struct {
	KeysSampled *V1State_Chunked_KeysSampled `protobuf:"bytes,2,opt,name=keys_sampled,json=keysSampled,proto3,oneof"`
}

type V1State_HeaderSent struct {
	HeaderSent *V1State_Chunked_HeaderSent `protobuf:"bytes,3,opt,name=header_sent,json=headerSent,proto3,oneof"`
}

type V1State_Ct1Received struct {
	Ct1Received *V1State_Chunked_Ct1Received `protobuf:"bytes,4,opt,name=ct1_received,json=ct1Received,proto3,oneof"`
}

type V1State_EkSentCt1Received struct {
	EkSentCt1Received *V1State_Chunked_EkSentCt1Received `protobuf:"bytes,5,opt,name=ek_sent_ct1_received,json=ekSentCt1Received,proto3,oneof"`
}

type V1State_NoHeaderReceived struct {
	// // send_ct ////
	NoHeaderReceived *V1State_Chunked_NoHeaderReceived `protobuf:"bytes,6,opt,name=no_header_received,json=noHeaderReceived,proto3,oneof"`
}

type V1State_HeaderReceived struct {
	HeaderReceived *V1State_Chunked_HeaderReceived `protobuf:"bytes,7,opt,name=header_received,json=headerReceived,proto3,oneof"`
}

type V1State_Ct1Sampled struct {
	Ct1Sampled *V1State_Chunked_Ct1Sampled `protobuf:"bytes,8,opt,name=ct1_sampled,json=ct1Sampled,proto3,oneof"`
}

type V1State_EkReceivedCt1Sampled struct {
	EkReceivedCt1Sampled *V1State_Chunked_EkReceivedCt1Sampled `protobuf:"bytes,9,opt,name=ek_received_ct1_sampled,json=ekReceivedCt1Sampled,proto3,oneof"`
}

type V1State_Ct1Acknowledged struct {
	Ct1Acknowledged *V1State_Chunked_Ct1Acknowledged `protobuf:"bytes,10,opt,name=ct1_acknowledged,json=ct1Acknowledged,proto3,oneof"`
}

type V1State_Ct2Sampled struct {
	Ct2Sampled *V1State_Chunked_Ct2Sampled `protobuf:"bytes,11,opt,name=ct2_sampled,json=ct2Sampled,proto3,oneof"`
}

func (*V1State_KeysUnsampled) isV1State_InnerState() {}

func (*V1State_KeysSampled) isV1State_InnerState() {}

func (*V1State_HeaderSent) isV1State_InnerState() {}

func (*V1State_Ct1Received) isV1State_InnerState() {}

func (*V1State_EkSentCt1Received) isV1State_InnerState() {}

func (*V1State_NoHeaderReceived) isV1State_InnerState() {}

func (*V1State_HeaderReceived) isV1State_InnerState() {}

func (*V1State_Ct1Sampled) isV1State_InnerState() {}

func (*V1State_EkReceivedCt1Sampled) isV1State_InnerState() {}

func (*V1State_Ct1Acknowledged) isV1State_InnerState() {}

func (*V1State_Ct2Sampled) isV1State_InnerState() {}

type Chain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direction     Direction              `protobuf:"varint,1,opt,name=direction,proto3,enum=signal.proto.pq_ratchet.Direction" json:"direction,omitempty"`
	CurrentEpoch  uint64                 `protobuf:"varint,2,opt,name=current_epoch,json=currentEpoch,proto3" json:"current_epoch,omitempty"`
	Links         []*Chain_Epoch         `protobuf:"bytes,3,rep,name=links,proto3" json:"links,omitempty"`
	NextRoot      []byte                 `protobuf:"bytes,4,opt,name=next_root,json=nextRoot,proto3" json:"next_root,omitempty"`
	SendEpoch     uint64                 `protobuf:"varint,5,opt,name=send_epoch,json=sendEpoch,proto3" json:"send_epoch,omitempty"`
	Params        *ChainParams           `protobuf:"bytes,6,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chain) Reset() {
	*x = Chain{}
	mi := &file_pq_ratchet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chain) ProtoMessage() {}

func (x *Chain) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chain.ProtoReflect.Descriptor instead.
func (*Chain) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{7}
}

func (x *Chain) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_A_2_B
}

func (x *Chain) GetCurrentEpoch() uint64 {
	if x != nil {
		return x.CurrentEpoch
	}
	return 0
}

func (x *Chain) GetLinks() []*Chain_Epoch {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *Chain) GetNextRoot() []byte {
	if x != nil {
		return x.NextRoot
	}
	return nil
}

func (x *Chain) GetSendEpoch() uint64 {
	if x != nil {
		return x.SendEpoch
	}
	return 0
}

func (x *Chain) GetParams() *ChainParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type ChainParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Disallow requesting a key that is more than MAX_JUMP ahead of `ctr`.
	// If zero, defaults to 25,000.
	MaxJump uint32 `protobuf:"varint,1,opt,name=max_jump,json=maxJump,proto3" json:"max_jump,omitempty"`
	// Keep around keys back to at least `ctr - MAX_OOO_KEYS`, in case an out-of-order
	// message comes in.  Messages older than this that arrive out-of-order
	// will not be able to be decrypted and will return Error::KeyTrimmed.
	MaxOooKeys    uint32 `protobuf:"varint,2,opt,name=max_ooo_keys,json=maxOooKeys,proto3" json:"max_ooo_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainParams) Reset() {
	*x = ChainParams{}
	mi := &file_pq_ratchet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainParams) ProtoMessage() {}

func (x *ChainParams) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainParams.ProtoReflect.Descriptor instead.
func (*ChainParams) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{8}
}

func (x *ChainParams) GetMaxJump() uint32 {
	if x != nil {
		return x.MaxJump
	}
	return 0
}

func (x *ChainParams) GetMaxOooKeys() uint32 {
	if x != nil {
		return x.MaxOooKeys
	}
	return 0
}

type PqRatchetState_VersionNegotiation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthKey       []byte                 `protobuf:"bytes,1,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`
	Direction     Direction              `protobuf:"varint,2,opt,name=direction,proto3,enum=signal.proto.pq_ratchet.Direction" json:"direction,omitempty"`
	MinVersion    Version                `protobuf:"varint,3,opt,name=min_version,json=minVersion,proto3,enum=signal.proto.pq_ratchet.Version" json:"min_version,omitempty"`
	ChainParams   *ChainParams           `protobuf:"bytes,4,opt,name=chain_params,json=chainParams,proto3" json:"chain_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PqRatchetState_VersionNegotiation) Reset() {
	*x = PqRatchetState_VersionNegotiation{}
	mi := &file_pq_ratchet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PqRatchetState_VersionNegotiation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PqRatchetState_VersionNegotiation) ProtoMessage() {}

func (x *PqRatchetState_VersionNegotiation) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PqRatchetState_VersionNegotiation.ProtoReflect.Descriptor instead.
func (*PqRatchetState_VersionNegotiation) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{2, 0}
}

func (x *PqRatchetState_VersionNegotiation) GetAuthKey() []byte {
	if x != nil {
		return x.AuthKey
	}
	return nil
}

func (x *PqRatchetState_VersionNegotiation) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_A_2_B
}

func (x *PqRatchetState_VersionNegotiation) GetMinVersion() Version {
	if x != nil {
		return x.MinVersion
	}
	return Version_V_0
}

func (x *PqRatchetState_VersionNegotiation) GetChainParams() *ChainParams {
	if x != nil {
		return x.ChainParams
	}
	return nil
}

type V1State_Unchunked struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1State_Unchunked) Reset() {
	*x = V1State_Unchunked{}
	mi := &file_pq_ratchet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1State_Unchunked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1State_Unchunked) ProtoMessage() {}

func (x *V1State_Unchunked) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1State_Unchunked.ProtoReflect.Descriptor instead.
func (*V1State_Unchunked) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{6, 0}
}

type V1State_Chunked struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1State_Chunked) Reset() {
	*x = V1State_Chunked{}
	mi := &file_pq_ratchet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1State_Chunked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1State_Chunked) ProtoMessage() {}

func (x *V1State_Chunked) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1State_Chunked.ProtoReflect.Descriptor instead.
func (*V1State_Chunked) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{6, 1}
}

// // send_ek ////
type V1State_Unchunked_KeysUnsampled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Auth          *Authenticator         `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1State_Unchunked_KeysUnsampled) Reset() {
	*x = V1State_Unchunked_KeysUnsampled{}
	mi := &file_pq_ratchet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1State_Unchunked_KeysUnsampled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1State_Unchunked_KeysUnsampled) ProtoMessage() {}

func (x *V1State_Unchunked_KeysUnsampled) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1State_Unchunked_KeysUnsampled.ProtoReflect.Descriptor instead.
func (*V1State_Unchunked_KeysUnsampled) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{6, 0, 0}
}

func (x *V1State_Unchunked_KeysUnsampled) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *V1State_Unchunked_KeysUnsampled) GetAuth() *Authenticator {
	if x != nil {
		return x.Auth
	}
	return nil
}

type V1State_Unchunked_HeaderSent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Auth          *Authenticator         `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	Ek            []byte                 `protobuf:"bytes,3,opt,name=ek,proto3" json:"ek,omitempty"`
	Dk            []byte                 `protobuf:"bytes,4,opt,name=dk,proto3" json:"dk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1State_Unchunked_HeaderSent) Reset() {
	*x = V1State_Unchunked_HeaderSent{}
	mi := &file_pq_ratchet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1State_Unchunked_HeaderSent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1State_Unchunked_HeaderSent) ProtoMessage() {}

func (x *V1State_Unchunked_HeaderSent) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1State_Unchunked_HeaderSent.ProtoReflect.Descriptor instead.
func (*V1State_Unchunked_HeaderSent) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{6, 0, 1}
}

func (x *V1State_Unchunked_HeaderSent) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *V1State_Unchunked_HeaderSent) GetAuth() *Authenticator {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *V1State_Unchunked_HeaderSent) GetEk() []byte {
	if x != nil {
		return x.Ek
	}
	return nil
}

func (x *V1State_Unchunked_HeaderSent) GetDk() []byte {
	if x != nil {
		return x.Dk
	}
	return nil
}

type V1State_Unchunked_EkSent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Auth          *Authenticator         `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	Dk            []byte                 `protobuf:"bytes,3,opt,name=dk,proto3" json:"dk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1State_Unchunked_EkSent) Reset() {
	*x = V1State_Unchunked_EkSent{}
	mi := &file_pq_ratchet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1State_Unchunked_EkSent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1State_Unchunked_EkSent) ProtoMessage() {}

func (x *V1State_Unchunked_EkSent) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1State_Unchunked_EkSent.ProtoReflect.Descriptor instead.
func (*V1State_Unchunked_EkSent) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{6, 0, 2}
}

func (x *V1State_Unchunked_EkSent) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *V1State_Unchunked_EkSent) GetAuth() *Authenticator {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *V1State_Unchunked_EkSent) GetDk() []byte {
	if x != nil {
		return x.Dk
	}
	return nil
}

type V1State_Unchunked_EkSentCt1Received struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Auth          *Authenticator         `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	Dk            []byte                 `protobuf:"bytes,3,opt,name=dk,proto3" json:"dk,omitempty"`
	Ct1           []byte                 `protobuf:"bytes,4,opt,name=ct1,proto3" json:"ct1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1State_Unchunked_EkSentCt1Received) Reset() {
	*x = V1State_Unchunked_EkSentCt1Received{}
	mi := &file_pq_ratchet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1State_Unchunked_EkSentCt1Received) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1State_Unchunked_EkSentCt1Received) ProtoMessage() {}

func (x *V1State_Unchunked_EkSentCt1Received) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1State_Unchunked_EkSentCt1Received.ProtoReflect.Descriptor instead.
func (*V1State_Unchunked_EkSentCt1Received) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{6, 0, 3}
}

func (x *V1State_Unchunked_EkSentCt1Received) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *V1State_Unchunked_EkSentCt1Received) GetAuth() *Authenticator {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *V1State_Unchunked_EkSentCt1Received) GetDk() []byte {
	if x != nil {
		return x.Dk
	}
	return nil
}

func (x *V1State_Unchunked_EkSentCt1Received) GetCt1() []byte {
	if x != nil {
		return x.Ct1
	}
	return nil
}

// // send_ct ////
type V1State_Unchunked_NoHeaderReceived struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Auth          *Authenticator         `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1State_Unchunked_NoHeaderReceived) Reset() {
	*x = V1State_Unchunked_NoHeaderReceived{}
	mi := &file_pq_ratchet_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1State_Unchunked_NoHeaderReceived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1State_Unchunked_NoHeaderReceived) ProtoMessage() {}

func (x *V1State_Unchunked_NoHeaderReceived) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1State_Unchunked_NoHeaderReceived.ProtoReflect.Descriptor instead.
func (*V1State_Unchunked_NoHeaderReceived) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{6, 0, 4}
}

func (x *V1State_Unchunked_NoHeaderReceived) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *V1State_Unchunked_NoHeaderReceived) GetAuth() *Authenticator {
	if x != nil {
		return x.Auth
	}
	return nil
}

type V1State_Unchunked_HeaderReceived struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Auth          *Authenticator         `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	Hdr           []byte                 `protobuf:"bytes,3,opt,name=hdr,proto3" json:"hdr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1State_Unchunked_HeaderReceived) Reset() {
	*x = V1State_Unchunked_HeaderReceived{}
	mi := &file_pq_ratchet_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1State_Unchunked_HeaderReceived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1State_Unchunked_HeaderReceived) ProtoMessage() {}

func (x *V1State_Unchunked_HeaderReceived) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1State_Unchunked_HeaderReceived.ProtoReflect.Descriptor instead.
func (*V1State_Unchunked_HeaderReceived) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{6, 0, 5}
}

func (x *V1State_Unchunked_HeaderReceived) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *V1State_Unchunked_HeaderReceived) GetAuth() *Authenticator {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *V1State_Unchunked_HeaderReceived) GetHdr() []byte {
	if x != nil {
		return x.Hdr
	}
	return nil
}

type V1State_Unchunked_EkReceived struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Auth          *Authenticator         `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	Hdr           []byte                 `protobuf:"bytes,3,opt,name=hdr,proto3" json:"hdr,omitempty"`
	Ek            []byte                 `protobuf:"bytes,4,opt,name=ek,proto3" json:"ek,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1State_Unchunked_EkReceived) Reset() {
	*x = V1State_Unchunked_EkReceived{}
	mi := &file_pq_ratchet_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1State_Unchunked_EkReceived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1State_Unchunked_EkReceived) ProtoMessage() {}

func (x *V1State_Unchunked_EkReceived) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1State_Unchunked_EkReceived.ProtoReflect.Descriptor instead.
func (*V1State_Unchunked_EkReceived) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{6, 0, 6}
}

func (x *V1State_Unchunked_EkReceived) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *V1State_Unchunked_EkReceived) GetAuth() *Authenticator {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *V1State_Unchunked_EkReceived) GetHdr() []byte {
	if x != nil {
		return x.Hdr
	}
	return nil
}

func (x *V1State_Unchunked_EkReceived) GetEk() []byte {
	if x != nil {
		return x.Ek
	}
	return nil
}

type V1State_Unchunked_Ct1Sent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Auth          *Authenticator         `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	Hdr           []byte                 `protobuf:"bytes,3,opt,name=hdr,proto3" json:"hdr,omitempty"`
	Es            []byte                 `protobuf:"bytes,4,opt,name=es,proto3" json:"es,omitempty"`
	Ct1           []byte                 `protobuf:"bytes,5,opt,name=ct1,proto3" json:"ct1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1State_Unchunked_Ct1Sent) Reset() {
	*x = V1State_Unchunked_Ct1Sent{}
	mi := &file_pq_ratchet_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1State_Unchunked_Ct1Sent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1State_Unchunked_Ct1Sent) ProtoMessage() {}

func (x *V1State_Unchunked_Ct1Sent) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1State_Unchunked_Ct1Sent.ProtoReflect.Descriptor instead.
func (*V1State_Unchunked_Ct1Sent) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{6, 0, 7}
}

func (x *V1State_Unchunked_Ct1Sent) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *V1State_Unchunked_Ct1Sent) GetAuth() *Authenticator {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *V1State_Unchunked_Ct1Sent) GetHdr() []byte {
	if x != nil {
		return x.Hdr
	}
	return nil
}

func (x *V1State_Unchunked_Ct1Sent) GetEs() []byte {
	if x != nil {
		return x.Es
	}
	return nil
}

func (x *V1State_Unchunked_Ct1Sent) GetCt1() []byte {
	if x != nil {
		return x.Ct1
	}
	return nil
}

type V1State_Unchunked_Ct1SentEkReceived struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Auth          *Authenticator         `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	Es            []byte                 `protobuf:"bytes,3,opt,name=es,proto3" json:"es,omitempty"`
	Ek            []byte                 `protobuf:"bytes,4,opt,name=ek,proto3" json:"ek,omitempty"`
	Ct1           []byte                 `protobuf:"bytes,5,opt,name=ct1,proto3" json:"ct1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1State_Unchunked_Ct1SentEkReceived) Reset() {
	*x = V1State_Unchunked_Ct1SentEkReceived{}
	mi := &file_pq_ratchet_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1State_Unchunked_Ct1SentEkReceived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1State_Unchunked_Ct1SentEkReceived) ProtoMessage() {}

func (x *V1State_Unchunked_Ct1SentEkReceived) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1State_Unchunked_Ct1SentEkReceived.ProtoReflect.Descriptor instead.
func (*V1State_Unchunked_Ct1SentEkReceived) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{6, 0, 8}
}

func (x *V1State_Unchunked_Ct1SentEkReceived) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *V1State_Unchunked_Ct1SentEkReceived) GetAuth() *Authenticator {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *V1State_Unchunked_Ct1SentEkReceived) GetEs() []byte {
	if x != nil {
		return x.Es
	}
	return nil
}

func (x *V1State_Unchunked_Ct1SentEkReceived) GetEk() []byte {
	if x != nil {
		return x.Ek
	}
	return nil
}

func (x *V1State_Unchunked_Ct1SentEkReceived) GetCt1() []byte {
	if x != nil {
		return x.Ct1
	}
	return nil
}

type V1State_Unchunked_Ct2Sent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Auth          *Authenticator         `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1State_Unchunked_Ct2Sent) Reset() {
	*x = V1State_Unchunked_Ct2Sent{}
	mi := &file_pq_ratchet_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1State_Unchunked_Ct2Sent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1State_Unchunked_Ct2Sent) ProtoMessage() {}

func (x *V1State_Unchunked_Ct2Sent) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1State_Unchunked_Ct2Sent.ProtoReflect.Descriptor instead.
func (*V1State_Unchunked_Ct2Sent) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{6, 0, 9}
}

func (x *V1State_Unchunked_Ct2Sent) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *V1State_Unchunked_Ct2Sent) GetAuth() *Authenticator {
	if x != nil {
		return x.Auth
	}
	return nil
}

// // send_ek ////
type V1State_Chunked_KeysUnsampled struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Uc            *V1State_Unchunked_KeysUnsampled `protobuf:"bytes,1,opt,name=uc,proto3" json:"uc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1State_Chunked_KeysUnsampled) Reset() {
	*x = V1State_Chunked_KeysUnsampled{}
	mi := &file_pq_ratchet_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1State_Chunked_KeysUnsampled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1State_Chunked_KeysUnsampled) ProtoMessage() {}

func (x *V1State_Chunked_KeysUnsampled) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1State_Chunked_KeysUnsampled.ProtoReflect.Descriptor instead.
func (*V1State_Chunked_KeysUnsampled) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{6, 1, 0}
}

func (x *V1State_Chunked_KeysUnsampled) GetUc() *V1State_Unchunked_KeysUnsampled {
	if x != nil {
		return x.Uc
	}
	return nil
}

type V1State_Chunked_KeysSampled struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Uc            *V1State_Unchunked_HeaderSent `protobuf:"bytes,1,opt,name=uc,proto3" json:"uc,omitempty"`
	SendingHdr    *PolynomialEncoder            `protobuf:"bytes,2,opt,name=sending_hdr,json=sendingHdr,proto3" json:"sending_hdr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1State_Chunked_KeysSampled) Reset() {
	*x = V1State_Chunked_KeysSampled{}
	mi := &file_pq_ratchet_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1State_Chunked_KeysSampled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1State_Chunked_KeysSampled) ProtoMessage() {}

func (x *V1State_Chunked_KeysSampled) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1State_Chunked_KeysSampled.ProtoReflect.Descriptor instead.
func (*V1State_Chunked_KeysSampled) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{6, 1, 1}
}

func (x *V1State_Chunked_KeysSampled) GetUc() *V1State_Unchunked_HeaderSent {
	if x != nil {
		return x.Uc
	}
	return nil
}

func (x *V1State_Chunked_KeysSampled) GetSendingHdr() *PolynomialEncoder {
	if x != nil {
		return x.SendingHdr
	}
	return nil
}

type V1State_Chunked_HeaderSent struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Uc            *V1State_Unchunked_EkSent `protobuf:"bytes,1,opt,name=uc,proto3" json:"uc,omitempty"`
	SendingEk     *PolynomialEncoder        `protobuf:"bytes,2,opt,name=sending_ek,json=sendingEk,proto3" json:"sending_ek,omitempty"`
	ReceivingCt1  *PolynomialDecoder        `protobuf:"bytes,3,opt,name=receiving_ct1,json=receivingCt1,proto3" json:"receiving_ct1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1State_Chunked_HeaderSent) Reset() {
	*x = V1State_Chunked_HeaderSent{}
	mi := &file_pq_ratchet_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1State_Chunked_HeaderSent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1State_Chunked_HeaderSent) ProtoMessage() {}

func (x *V1State_Chunked_HeaderSent) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1State_Chunked_HeaderSent.ProtoReflect.Descriptor instead.
func (*V1State_Chunked_HeaderSent) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{6, 1, 2}
}

func (x *V1State_Chunked_HeaderSent) GetUc() *V1State_Unchunked_EkSent {
	if x != nil {
		return x.Uc
	}
	return nil
}

func (x *V1State_Chunked_HeaderSent) GetSendingEk() *PolynomialEncoder {
	if x != nil {
		return x.SendingEk
	}
	return nil
}

func (x *V1State_Chunked_HeaderSent) GetReceivingCt1() *PolynomialDecoder {
	if x != nil {
		return x.ReceivingCt1
	}
	return nil
}

type V1State_Chunked_Ct1Received struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Uc            *V1State_Unchunked_EkSentCt1Received `protobuf:"bytes,1,opt,name=uc,proto3" json:"uc,omitempty"`
	SendingEk     *PolynomialEncoder                   `protobuf:"bytes,2,opt,name=sending_ek,json=sendingEk,proto3" json:"sending_ek,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1State_Chunked_Ct1Received) Reset() {
	*x = V1State_Chunked_Ct1Received{}
	mi := &file_pq_ratchet_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1State_Chunked_Ct1Received) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1State_Chunked_Ct1Received) ProtoMessage() {}

func (x *V1State_Chunked_Ct1Received) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1State_Chunked_Ct1Received.ProtoReflect.Descriptor instead.
func (*V1State_Chunked_Ct1Received) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{6, 1, 3}
}

func (x *V1State_Chunked_Ct1Received) GetUc() *V1State_Unchunked_EkSentCt1Received {
	if x != nil {
		return x.Uc
	}
	return nil
}

func (x *V1State_Chunked_Ct1Received) GetSendingEk() *PolynomialEncoder {
	if x != nil {
		return x.SendingEk
	}
	return nil
}

type V1State_Chunked_EkSentCt1Received struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Uc            *V1State_Unchunked_EkSentCt1Received `protobuf:"bytes,1,opt,name=uc,proto3" json:"uc,omitempty"`
	ReceivingCt2  *PolynomialDecoder                   `protobuf:"bytes,3,opt,name=receiving_ct2,json=receivingCt2,proto3" json:"receiving_ct2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1State_Chunked_EkSentCt1Received) Reset() {
	*x = V1State_Chunked_EkSentCt1Received{}
	mi := &file_pq_ratchet_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1State_Chunked_EkSentCt1Received) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1State_Chunked_EkSentCt1Received) ProtoMessage() {}

func (x *V1State_Chunked_EkSentCt1Received) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1State_Chunked_EkSentCt1Received.ProtoReflect.Descriptor instead.
func (*V1State_Chunked_EkSentCt1Received) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{6, 1, 4}
}

func (x *V1State_Chunked_EkSentCt1Received) GetUc() *V1State_Unchunked_EkSentCt1Received {
	if x != nil {
		return x.Uc
	}
	return nil
}

func (x *V1State_Chunked_EkSentCt1Received) GetReceivingCt2() *PolynomialDecoder {
	if x != nil {
		return x.ReceivingCt2
	}
	return nil
}

// // send_ct ////
type V1State_Chunked_NoHeaderReceived struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Uc            *V1State_Unchunked_NoHeaderReceived `protobuf:"bytes,1,opt,name=uc,proto3" json:"uc,omitempty"`
	ReceivingHdr  *PolynomialDecoder                  `protobuf:"bytes,2,opt,name=receiving_hdr,json=receivingHdr,proto3" json:"receiving_hdr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1State_Chunked_NoHeaderReceived) Reset() {
	*x = V1State_Chunked_NoHeaderReceived{}
	mi := &file_pq_ratchet_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1State_Chunked_NoHeaderReceived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1State_Chunked_NoHeaderReceived) ProtoMessage() {}

func (x *V1State_Chunked_NoHeaderReceived) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1State_Chunked_NoHeaderReceived.ProtoReflect.Descriptor instead.
func (*V1State_Chunked_NoHeaderReceived) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{6, 1, 5}
}

func (x *V1State_Chunked_NoHeaderReceived) GetUc() *V1State_Unchunked_NoHeaderReceived {
	if x != nil {
		return x.Uc
	}
	return nil
}

func (x *V1State_Chunked_NoHeaderReceived) GetReceivingHdr() *PolynomialDecoder {
	if x != nil {
		return x.ReceivingHdr
	}
	return nil
}

type V1State_Chunked_HeaderReceived struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Uc            *V1State_Unchunked_HeaderReceived `protobuf:"bytes,1,opt,name=uc,proto3" json:"uc,omitempty"`
	ReceivingEk   *PolynomialDecoder                `protobuf:"bytes,2,opt,name=receiving_ek,json=receivingEk,proto3" json:"receiving_ek,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1State_Chunked_HeaderReceived) Reset() {
	*x = V1State_Chunked_HeaderReceived{}
	mi := &file_pq_ratchet_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1State_Chunked_HeaderReceived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1State_Chunked_HeaderReceived) ProtoMessage() {}

func (x *V1State_Chunked_HeaderReceived) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1State_Chunked_HeaderReceived.ProtoReflect.Descriptor instead.
func (*V1State_Chunked_HeaderReceived) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{6, 1, 6}
}

func (x *V1State_Chunked_HeaderReceived) GetUc() *V1State_Unchunked_HeaderReceived {
	if x != nil {
		return x.Uc
	}
	return nil
}

func (x *V1State_Chunked_HeaderReceived) GetReceivingEk() *PolynomialDecoder {
	if x != nil {
		return x.ReceivingEk
	}
	return nil
}

type V1State_Chunked_Ct1Sampled struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Uc            *V1State_Unchunked_Ct1Sent `protobuf:"bytes,1,opt,name=uc,proto3" json:"uc,omitempty"`
	SendingCt1    *PolynomialEncoder         `protobuf:"bytes,2,opt,name=sending_ct1,json=sendingCt1,proto3" json:"sending_ct1,omitempty"`
	ReceivingEk   *PolynomialDecoder         `protobuf:"bytes,3,opt,name=receiving_ek,json=receivingEk,proto3" json:"receiving_ek,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1State_Chunked_Ct1Sampled) Reset() {
	*x = V1State_Chunked_Ct1Sampled{}
	mi := &file_pq_ratchet_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1State_Chunked_Ct1Sampled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1State_Chunked_Ct1Sampled) ProtoMessage() {}

func (x *V1State_Chunked_Ct1Sampled) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1State_Chunked_Ct1Sampled.ProtoReflect.Descriptor instead.
func (*V1State_Chunked_Ct1Sampled) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{6, 1, 7}
}

func (x *V1State_Chunked_Ct1Sampled) GetUc() *V1State_Unchunked_Ct1Sent {
	if x != nil {
		return x.Uc
	}
	return nil
}

func (x *V1State_Chunked_Ct1Sampled) GetSendingCt1() *PolynomialEncoder {
	if x != nil {
		return x.SendingCt1
	}
	return nil
}

func (x *V1State_Chunked_Ct1Sampled) GetReceivingEk() *PolynomialDecoder {
	if x != nil {
		return x.ReceivingEk
	}
	return nil
}

type V1State_Chunked_EkReceivedCt1Sampled struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Uc            *V1State_Unchunked_Ct1SentEkReceived `protobuf:"bytes,1,opt,name=uc,proto3" json:"uc,omitempty"`
	SendingCt1    *PolynomialEncoder                   `protobuf:"bytes,2,opt,name=sending_ct1,json=sendingCt1,proto3" json:"sending_ct1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1State_Chunked_EkReceivedCt1Sampled) Reset() {
	*x = V1State_Chunked_EkReceivedCt1Sampled{}
	mi := &file_pq_ratchet_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1State_Chunked_EkReceivedCt1Sampled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1State_Chunked_EkReceivedCt1Sampled) ProtoMessage() {}

func (x *V1State_Chunked_EkReceivedCt1Sampled) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1State_Chunked_EkReceivedCt1Sampled.ProtoReflect.Descriptor instead.
func (*V1State_Chunked_EkReceivedCt1Sampled) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{6, 1, 8}
}

func (x *V1State_Chunked_EkReceivedCt1Sampled) GetUc() *V1State_Unchunked_Ct1SentEkReceived {
	if x != nil {
		return x.Uc
	}
	return nil
}

func (x *V1State_Chunked_EkReceivedCt1Sampled) GetSendingCt1() *PolynomialEncoder {
	if x != nil {
		return x.SendingCt1
	}
	return nil
}

type V1State_Chunked_Ct1Acknowledged struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Uc            *V1State_Unchunked_Ct1Sent `protobuf:"bytes,1,opt,name=uc,proto3" json:"uc,omitempty"`
	ReceivingEk   *PolynomialDecoder         `protobuf:"bytes,2,opt,name=receiving_ek,json=receivingEk,proto3" json:"receiving_ek,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1State_Chunked_Ct1Acknowledged) Reset() {
	*x = V1State_Chunked_Ct1Acknowledged{}
	mi := &file_pq_ratchet_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1State_Chunked_Ct1Acknowledged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1State_Chunked_Ct1Acknowledged) ProtoMessage() {}

func (x *V1State_Chunked_Ct1Acknowledged) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1State_Chunked_Ct1Acknowledged.ProtoReflect.Descriptor instead.
func (*V1State_Chunked_Ct1Acknowledged) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{6, 1, 9}
}

func (x *V1State_Chunked_Ct1Acknowledged) GetUc() *V1State_Unchunked_Ct1Sent {
	if x != nil {
		return x.Uc
	}
	return nil
}

func (x *V1State_Chunked_Ct1Acknowledged) GetReceivingEk() *PolynomialDecoder {
	if x != nil {
		return x.ReceivingEk
	}
	return nil
}

type V1State_Chunked_Ct2Sampled struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Uc            *V1State_Unchunked_Ct2Sent `protobuf:"bytes,1,opt,name=uc,proto3" json:"uc,omitempty"`
	SendingCt2    *PolynomialEncoder         `protobuf:"bytes,2,opt,name=sending_ct2,json=sendingCt2,proto3" json:"sending_ct2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *V1State_Chunked_Ct2Sampled) Reset() {
	*x = V1State_Chunked_Ct2Sampled{}
	mi := &file_pq_ratchet_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V1State_Chunked_Ct2Sampled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1State_Chunked_Ct2Sampled) ProtoMessage() {}

func (x *V1State_Chunked_Ct2Sampled) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1State_Chunked_Ct2Sampled.ProtoReflect.Descriptor instead.
func (*V1State_Chunked_Ct2Sampled) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{6, 1, 10}
}

func (x *V1State_Chunked_Ct2Sampled) GetUc() *V1State_Unchunked_Ct2Sent {
	if x != nil {
		return x.Uc
	}
	return nil
}

func (x *V1State_Chunked_Ct2Sampled) GetSendingCt2() *PolynomialEncoder {
	if x != nil {
		return x.SendingCt2
	}
	return nil
}

type Chain_Epoch struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Send          *Chain_Epoch_EpochDirection `protobuf:"bytes,1,opt,name=send,proto3" json:"send,omitempty"`
	Recv          *Chain_Epoch_EpochDirection `protobuf:"bytes,2,opt,name=recv,proto3" json:"recv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chain_Epoch) Reset() {
	*x = Chain_Epoch{}
	mi := &file_pq_ratchet_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chain_Epoch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chain_Epoch) ProtoMessage() {}

func (x *Chain_Epoch) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chain_Epoch.ProtoReflect.Descriptor instead.
func (*Chain_Epoch) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{7, 0}
}

func (x *Chain_Epoch) GetSend() *Chain_Epoch_EpochDirection {
	if x != nil {
		return x.Send
	}
	return nil
}

func (x *Chain_Epoch) GetRecv() *Chain_Epoch_EpochDirection {
	if x != nil {
		return x.Recv
	}
	return nil
}

type Chain_Epoch_EpochDirection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ctr           uint32                 `protobuf:"varint,1,opt,name=ctr,proto3" json:"ctr,omitempty"`
	Next          []byte                 `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	Prev          []byte                 `protobuf:"bytes,3,opt,name=prev,proto3" json:"prev,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chain_Epoch_EpochDirection) Reset() {
	*x = Chain_Epoch_EpochDirection{}
	mi := &file_pq_ratchet_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chain_Epoch_EpochDirection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chain_Epoch_EpochDirection) ProtoMessage() {}

func (x *Chain_Epoch_EpochDirection) ProtoReflect() protoreflect.Message {
	mi := &file_pq_ratchet_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chain_Epoch_EpochDirection.ProtoReflect.Descriptor instead.
func (*Chain_Epoch_EpochDirection) Descriptor() ([]byte, []int) {
	return file_pq_ratchet_proto_rawDescGZIP(), []int{7, 0, 0}
}

func (x *Chain_Epoch_EpochDirection) GetCtr() uint32 {
	if x != nil {
		return x.Ctr
	}
	return 0
}

func (x *Chain_Epoch_EpochDirection) GetNext() []byte {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *Chain_Epoch_EpochDirection) GetPrev() []byte {
	if x != nil {
		return x.Prev
	}
	return nil
}

var File_pq_ratchet_proto protoreflect.FileDescriptor

const file_pq_ratchet_proto_rawDesc = "" +
	"\n" +
	"\x10pq_ratchet.proto\x12\x17signal.proto.pq_ratchet\"M\n" +
	"\x11PolynomialEncoder\x12\x10\n" +
	"\x03idx\x18\x01 \x01(\rR\x03idx\x12\x10\n" +
	"\x03pts\x18\x02 \x03(\fR\x03pts\x12\x14\n" +
	"\x05polys\x18\x03 \x03(\fR\x05polys\"{\n" +
	"\x11PolynomialDecoder\x12\x1d\n" +
	"\n" +
	"pts_needed\x18\x01 \x01(\rR\tptsNeeded\x12\x14\n" +
	"\x05polys\x18\x02 \x01(\rR\x05polys\x12\x10\n" +
	"\x03pts\x18\x03 \x03(\fR\x03pts\x12\x1f\n" +
	"\vis_complete\x18\x04 \x01(\bR\n" +
	"isComplete\"\xf0\x03\n" +
	"\x0ePqRatchetState\x12k\n" +
	"\x13version_negotiation\x18\x01 \x01(\v2:.signal.proto.pq_ratchet.PqRatchetState.VersionNegotiationR\x12versionNegotiation\x124\n" +
	"\x05chain\x18\x02 \x01(\v2\x1e.signal.proto.pq_ratchet.ChainR\x05chain\x122\n" +
	"\x02v1\x18\x03 \x01(\v2 .signal.proto.pq_ratchet.V1StateH\x00R\x02v1\x1a\xfd\x01\n" +
	"\x12VersionNegotiation\x12\x19\n" +
	"\bauth_key\x18\x01 \x01(\fR\aauthKey\x12@\n" +
	"\tdirection\x18\x02 \x01(\x0e2\".signal.proto.pq_ratchet.DirectionR\tdirection\x12A\n" +
	"\vmin_version\x18\x03 \x01(\x0e2 .signal.proto.pq_ratchet.VersionR\n" +
	"minVersion\x12G\n" +
	"\fchain_params\x18\x04 \x01(\v2$.signal.proto.pq_ratchet.ChainParamsR\vchainParamsB\a\n" +
	"\x05inner\"1\n" +
	"\x05Chunk\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xe9\x02\n" +
	"\x05V1Msg\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\x122\n" +
	"\x03hdr\x18\x03 \x01(\v2\x1e.signal.proto.pq_ratchet.ChunkH\x00R\x03hdr\x120\n" +
	"\x02ek\x18\x04 \x01(\v2\x1e.signal.proto.pq_ratchet.ChunkH\x00R\x02ek\x12>\n" +
	"\n" +
	"ek_ct1_ack\x18\x05 \x01(\v2\x1e.signal.proto.pq_ratchet.ChunkH\x00R\bekCt1Ack\x12\x19\n" +
	"\act1_ack\x18\x06 \x01(\bH\x00R\x06ct1Ack\x122\n" +
	"\x03ct1\x18\a \x01(\v2\x1e.signal.proto.pq_ratchet.ChunkH\x00R\x03ct1\x122\n" +
	"\x03ct2\x18\b \x01(\v2\x1e.signal.proto.pq_ratchet.ChunkH\x00R\x03ct2B\v\n" +
	"\tinner_msg\"C\n" +
	"\rAuthenticator\x12\x19\n" +
	"\broot_key\x18\x01 \x01(\fR\arootKey\x12\x17\n" +
	"\amac_key\x18\x02 \x01(\fR\x06macKey\"\xc4!\n" +
	"\aV1State\x12_\n" +
	"\x0ekeys_unsampled\x18\x01 \x01(\v26.signal.proto.pq_ratchet.V1State.Chunked.KeysUnsampledH\x00R\rkeysUnsampled\x12Y\n" +
	"\fkeys_sampled\x18\x02 \x01(\v24.signal.proto.pq_ratchet.V1State.Chunked.KeysSampledH\x00R\vkeysSampled\x12V\n" +
	"\vheader_sent\x18\x03 \x01(\v23.signal.proto.pq_ratchet.V1State.Chunked.HeaderSentH\x00R\n" +
	"headerSent\x12Y\n" +
	"\fct1_received\x18\x04 \x01(\v24.signal.proto.pq_ratchet.V1State.Chunked.Ct1ReceivedH\x00R\vct1Received\x12m\n" +
	"\x14ek_sent_ct1_received\x18\x05 \x01(\v2:.signal.proto.pq_ratchet.V1State.Chunked.EkSentCt1ReceivedH\x00R\x11ekSentCt1Received\x12i\n" +
	"\x12no_header_received\x18\x06 \x01(\v29.signal.proto.pq_ratchet.V1State.Chunked.NoHeaderReceivedH\x00R\x10noHeaderReceived\x12b\n" +
	"\x0fheader_received\x18\a \x01(\v27.signal.proto.pq_ratchet.V1State.Chunked.HeaderReceivedH\x00R\x0eheaderReceived\x12V\n" +
	"\vct1_sampled\x18\b \x01(\v23.signal.proto.pq_ratchet.V1State.Chunked.Ct1SampledH\x00R\n" +
	"ct1Sampled\x12v\n" +
	"\x17ek_received_ct1_sampled\x18\t \x01(\v2=.signal.proto.pq_ratchet.V1State.Chunked.EkReceivedCt1SampledH\x00R\x14ekReceivedCt1Sampled\x12e\n" +
	"\x10ct1_acknowledged\x18\n" +
	" \x01(\v28.signal.proto.pq_ratchet.V1State.Chunked.Ct1AcknowledgedH\x00R\x0fct1Acknowledged\x12V\n" +
	"\vct2_sampled\x18\v \x01(\v23.signal.proto.pq_ratchet.V1State.Chunked.Ct2SampledH\x00R\n" +
	"ct2Sampled\x1a\xcc\t\n" +
	"\tUnchunked\x1aa\n" +
	"\rKeysUnsampled\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12:\n" +
	"\x04auth\x18\x02 \x01(\v2&.signal.proto.pq_ratchet.AuthenticatorR\x04auth\x1a~\n" +
	"\n" +
	"HeaderSent\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12:\n" +
	"\x04auth\x18\x02 \x01(\v2&.signal.proto.pq_ratchet.AuthenticatorR\x04auth\x12\x0e\n" +
	"\x02ek\x18\x03 \x01(\fR\x02ek\x12\x0e\n" +
	"\x02dk\x18\x04 \x01(\fR\x02dk\x1aj\n" +
	"\x06EkSent\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12:\n" +
	"\x04auth\x18\x02 \x01(\v2&.signal.proto.pq_ratchet.AuthenticatorR\x04auth\x12\x0e\n" +
	"\x02dk\x18\x03 \x01(\fR\x02dk\x1a\x87\x01\n" +
	"\x11EkSentCt1Received\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12:\n" +
	"\x04auth\x18\x02 \x01(\v2&.signal.proto.pq_ratchet.AuthenticatorR\x04auth\x12\x0e\n" +
	"\x02dk\x18\x03 \x01(\fR\x02dk\x12\x10\n" +
	"\x03ct1\x18\x04 \x01(\fR\x03ct1\x1ad\n" +
	"\x10NoHeaderReceived\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12:\n" +
	"\x04auth\x18\x02 \x01(\v2&.signal.proto.pq_ratchet.AuthenticatorR\x04auth\x1at\n" +
	"\x0eHeaderReceived\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12:\n" +
	"\x04auth\x18\x02 \x01(\v2&.signal.proto.pq_ratchet.AuthenticatorR\x04auth\x12\x10\n" +
	"\x03hdr\x18\x03 \x01(\fR\x03hdr\x1a\x80\x01\n" +
	"\n" +
	"EkReceived\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12:\n" +
	"\x04auth\x18\x02 \x01(\v2&.signal.proto.pq_ratchet.AuthenticatorR\x04auth\x12\x10\n" +
	"\x03hdr\x18\x03 \x01(\fR\x03hdr\x12\x0e\n" +
	"\x02ek\x18\x04 \x01(\fR\x02ek\x1a\x8f\x01\n" +
	"\aCt1Sent\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12:\n" +
	"\x04auth\x18\x02 \x01(\v2&.signal.proto.pq_ratchet.AuthenticatorR\x04auth\x12\x10\n" +
	"\x03hdr\x18\x03 \x01(\fR\x03hdr\x12\x0e\n" +
	"\x02es\x18\x04 \x01(\fR\x02es\x12\x10\n" +
	"\x03ct1\x18\x05 \x01(\fR\x03ct1\x1a\x97\x01\n" +
	"\x11Ct1SentEkReceived\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12:\n" +
	"\x04auth\x18\x02 \x01(\v2&.signal.proto.pq_ratchet.AuthenticatorR\x04auth\x12\x0e\n" +
	"\x02es\x18\x03 \x01(\fR\x02es\x12\x0e\n" +
	"\x02ek\x18\x04 \x01(\fR\x02ek\x12\x10\n" +
	"\x03ct1\x18\x05 \x01(\fR\x03ct1\x1a[\n" +
	"\aCt2Sent\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12:\n" +
	"\x04auth\x18\x02 \x01(\v2&.signal.proto.pq_ratchet.AuthenticatorR\x04auth\x1a\x9e\x0f\n" +
	"\aChunked\x1aY\n" +
	"\rKeysUnsampled\x12H\n" +
	"\x02uc\x18\x01 \x01(\v28.signal.proto.pq_ratchet.V1State.Unchunked.KeysUnsampledR\x02uc\x1a\xa1\x01\n" +
	"\vKeysSampled\x12E\n" +
	"\x02uc\x18\x01 \x01(\v25.signal.proto.pq_ratchet.V1State.Unchunked.HeaderSentR\x02uc\x12K\n" +
	"\vsending_hdr\x18\x02 \x01(\v2*.signal.proto.pq_ratchet.PolynomialEncoderR\n" +
	"sendingHdr\x1a\xeb\x01\n" +
	"\n" +
	"HeaderSent\x12A\n" +
	"\x02uc\x18\x01 \x01(\v21.signal.proto.pq_ratchet.V1State.Unchunked.EkSentR\x02uc\x12I\n" +
	"\n" +
	"sending_ek\x18\x02 \x01(\v2*.signal.proto.pq_ratchet.PolynomialEncoderR\tsendingEk\x12O\n" +
	"\rreceiving_ct1\x18\x03 \x01(\v2*.signal.proto.pq_ratchet.PolynomialDecoderR\freceivingCt1\x1a\xa6\x01\n" +
	"\vCt1Received\x12L\n" +
	"\x02uc\x18\x01 \x01(\v2<.signal.proto.pq_ratchet.V1State.Unchunked.EkSentCt1ReceivedR\x02uc\x12I\n" +
	"\n" +
	"sending_ek\x18\x02 \x01(\v2*.signal.proto.pq_ratchet.PolynomialEncoderR\tsendingEk\x1a\xb2\x01\n" +
	"\x11EkSentCt1Received\x12L\n" +
	"\x02uc\x18\x01 \x01(\v2<.signal.proto.pq_ratchet.V1State.Unchunked.EkSentCt1ReceivedR\x02uc\x12O\n" +
	"\rreceiving_ct2\x18\x03 \x01(\v2*.signal.proto.pq_ratchet.PolynomialDecoderR\freceivingCt2\x1a\xb0\x01\n" +
	"\x10NoHeaderReceived\x12K\n" +
	"\x02uc\x18\x01 \x01(\v2;.signal.proto.pq_ratchet.V1State.Unchunked.NoHeaderReceivedR\x02uc\x12O\n" +
	"\rreceiving_hdr\x18\x02 \x01(\v2*.signal.proto.pq_ratchet.PolynomialDecoderR\freceivingHdr\x1a\xaa\x01\n" +
	"\x0eHeaderReceived\x12I\n" +
	"\x02uc\x18\x01 \x01(\v29.signal.proto.pq_ratchet.V1State.Unchunked.HeaderReceivedR\x02uc\x12M\n" +
	"\freceiving_ek\x18\x02 \x01(\v2*.signal.proto.pq_ratchet.PolynomialDecoderR\vreceivingEk\x1a\xec\x01\n" +
	"\n" +
	"Ct1Sampled\x12B\n" +
	"\x02uc\x18\x01 \x01(\v22.signal.proto.pq_ratchet.V1State.Unchunked.Ct1SentR\x02uc\x12K\n" +
	"\vsending_ct1\x18\x02 \x01(\v2*.signal.proto.pq_ratchet.PolynomialEncoderR\n" +
	"sendingCt1\x12M\n" +
	"\freceiving_ek\x18\x03 \x01(\v2*.signal.proto.pq_ratchet.PolynomialDecoderR\vreceivingEk\x1a\xb1\x01\n" +
	"\x14EkReceivedCt1Sampled\x12L\n" +
	"\x02uc\x18\x01 \x01(\v2<.signal.proto.pq_ratchet.V1State.Unchunked.Ct1SentEkReceivedR\x02uc\x12K\n" +
	"\vsending_ct1\x18\x02 \x01(\v2*.signal.proto.pq_ratchet.PolynomialEncoderR\n" +
	"sendingCt1\x1a\xa4\x01\n" +
	"\x0fCt1Acknowledged\x12B\n" +
	"\x02uc\x18\x01 \x01(\v22.signal.proto.pq_ratchet.V1State.Unchunked.Ct1SentR\x02uc\x12M\n" +
	"\freceiving_ek\x18\x02 \x01(\v2*.signal.proto.pq_ratchet.PolynomialDecoderR\vreceivingEk\x1a\x9d\x01\n" +
	"\n" +
	"Ct2Sampled\x12B\n" +
	"\x02uc\x18\x01 \x01(\v22.signal.proto.pq_ratchet.V1State.Unchunked.Ct2SentR\x02uc\x12K\n" +
	"\vsending_ct2\x18\x02 \x01(\v2*.signal.proto.pq_ratchet.PolynomialEncoderR\n" +
	"sendingCt2B\r\n" +
	"\vinner_state\"\x8c\x04\n" +
	"\x05Chain\x12@\n" +
	"\tdirection\x18\x01 \x01(\x0e2\".signal.proto.pq_ratchet.DirectionR\tdirection\x12#\n" +
	"\rcurrent_epoch\x18\x02 \x01(\x04R\fcurrentEpoch\x12:\n" +
	"\x05links\x18\x03 \x03(\v2$.signal.proto.pq_ratchet.Chain.EpochR\x05links\x12\x1b\n" +
	"\tnext_root\x18\x04 \x01(\fR\bnextRoot\x12\x1d\n" +
	"\n" +
	"send_epoch\x18\x05 \x01(\x04R\tsendEpoch\x12<\n" +
	"\x06params\x18\x06 \x01(\v2$.signal.proto.pq_ratchet.ChainParamsR\x06params\x1a\xe5\x01\n" +
	"\x05Epoch\x12G\n" +
	"\x04send\x18\x01 \x01(\v23.signal.proto.pq_ratchet.Chain.Epoch.EpochDirectionR\x04send\x12G\n" +
	"\x04recv\x18\x02 \x01(\v23.signal.proto.pq_ratchet.Chain.Epoch.EpochDirectionR\x04recv\x1aJ\n" +
	"\x0eEpochDirection\x12\x10\n" +
	"\x03ctr\x18\x01 \x01(\rR\x03ctr\x12\x12\n" +
	"\x04next\x18\x02 \x01(\fR\x04next\x12\x12\n" +
	"\x04prev\x18\x03 \x01(\fR\x04prev\"J\n" +
	"\vChainParams\x12\x19\n" +
	"\bmax_jump\x18\x01 \x01(\rR\amaxJump\x12 \n" +
	"\fmax_ooo_keys\x18\x02 \x01(\rR\n" +
	"maxOooKeys*\x1b\n" +
	"\aVersion\x12\a\n" +
	"\x03V_0\x10\x00\x12\a\n" +
	"\x03V_1\x10\x01*!\n" +
	"\tDirection\x12\t\n" +
	"\x05A_2_B\x10\x00\x12\t\n" +
	"\x05B_2_A\x10\x01B+Z)github.com/GoCodeAlone/libsignal-go/protob\x06proto3"

var (
	file_pq_ratchet_proto_rawDescOnce sync.Once
	file_pq_ratchet_proto_rawDescData []byte
)

func file_pq_ratchet_proto_rawDescGZIP() []byte {
	file_pq_ratchet_proto_rawDescOnce.Do(func() {
		file_pq_ratchet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pq_ratchet_proto_rawDesc), len(file_pq_ratchet_proto_rawDesc)))
	})
	return file_pq_ratchet_proto_rawDescData
}

var file_pq_ratchet_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pq_ratchet_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_pq_ratchet_proto_goTypes = []any{
	(Version)(0),                                 // 0: signal.proto.pq_ratchet.Version
	(Direction)(0),                               // 1: signal.proto.pq_ratchet.Direction
	(*PolynomialEncoder)(nil),                    // 2: signal.proto.pq_ratchet.PolynomialEncoder
	(*PolynomialDecoder)(nil),                    // 3: signal.proto.pq_ratchet.PolynomialDecoder
	(*PqRatchetState)(nil),                       // 4: signal.proto.pq_ratchet.PqRatchetState
	(*Chunk)(nil),                                // 5: signal.proto.pq_ratchet.Chunk
	(*V1Msg)(nil),                                // 6: signal.proto.pq_ratchet.V1Msg
	(*Authenticator)(nil),                        // 7: signal.proto.pq_ratchet.Authenticator
	(*V1State)(nil),                              // 8: signal.proto.pq_ratchet.V1State
	(*Chain)(nil),                                // 9: signal.proto.pq_ratchet.Chain
	(*ChainParams)(nil),                          // 10: signal.proto.pq_ratchet.ChainParams
	(*PqRatchetState_VersionNegotiation)(nil),    // 11: signal.proto.pq_ratchet.PqRatchetState.VersionNegotiation
	(*V1State_Unchunked)(nil),                    // 12: signal.proto.pq_ratchet.V1State.Unchunked
	(*V1State_Chunked)(nil),                      // 13: signal.proto.pq_ratchet.V1State.Chunked
	(*V1State_Unchunked_KeysUnsampled)(nil),      // 14: signal.proto.pq_ratchet.V1State.Unchunked.KeysUnsampled
	(*V1State_Unchunked_HeaderSent)(nil),         // 15: signal.proto.pq_ratchet.V1State.Unchunked.HeaderSent
	(*V1State_Unchunked_EkSent)(nil),             // 16: signal.proto.pq_ratchet.V1State.Unchunked.EkSent
	(*V1State_Unchunked_EkSentCt1Received)(nil),  // 17: signal.proto.pq_ratchet.V1State.Unchunked.EkSentCt1Received
	(*V1State_Unchunked_NoHeaderReceived)(nil),   // 18: signal.proto.pq_ratchet.V1State.Unchunked.NoHeaderReceived
	(*V1State_Unchunked_HeaderReceived)(nil),     // 19: signal.proto.pq_ratchet.V1State.Unchunked.HeaderReceived
	(*V1State_Unchunked_EkReceived)(nil),         // 20: signal.proto.pq_ratchet.V1State.Unchunked.EkReceived
	(*V1State_Unchunked_Ct1Sent)(nil),            // 21: signal.proto.pq_ratchet.V1State.Unchunked.Ct1Sent
	(*V1State_Unchunked_Ct1SentEkReceived)(nil),  // 22: signal.proto.pq_ratchet.V1State.Unchunked.Ct1SentEkReceived
	(*V1State_Unchunked_Ct2Sent)(nil),            // 23: signal.proto.pq_ratchet.V1State.Unchunked.Ct2Sent
	(*V1State_Chunked_KeysUnsampled)(nil),        // 24: signal.proto.pq_ratchet.V1State.Chunked.KeysUnsampled
	(*V1State_Chunked_KeysSampled)(nil),          // 25: signal.proto.pq_ratchet.V1State.Chunked.KeysSampled
	(*V1State_Chunked_HeaderSent)(nil),           // 26: signal.proto.pq_ratchet.V1State.Chunked.HeaderSent
	(*V1State_Chunked_Ct1Received)(nil),          // 27: signal.proto.pq_ratchet.V1State.Chunked.Ct1Received
	(*V1State_Chunked_EkSentCt1Received)(nil),    // 28: signal.proto.pq_ratchet.V1State.Chunked.EkSentCt1Received
	(*V1State_Chunked_NoHeaderReceived)(nil),     // 29: signal.proto.pq_ratchet.V1State.Chunked.NoHeaderReceived
	(*V1State_Chunked_HeaderReceived)(nil),       // 30: signal.proto.pq_ratchet.V1State.Chunked.HeaderReceived
	(*V1State_Chunked_Ct1Sampled)(nil),           // 31: signal.proto.pq_ratchet.V1State.Chunked.Ct1Sampled
	(*V1State_Chunked_EkReceivedCt1Sampled)(nil), // 32: signal.proto.pq_ratchet.V1State.Chunked.EkReceivedCt1Sampled
	(*V1State_Chunked_Ct1Acknowledged)(nil),      // 33: signal.proto.pq_ratchet.V1State.Chunked.Ct1Acknowledged
	(*V1State_Chunked_Ct2Sampled)(nil),           // 34: signal.proto.pq_ratchet.V1State.Chunked.Ct2Sampled
	(*Chain_Epoch)(nil),                          // 35: signal.proto.pq_ratchet.Chain.Epoch
	(*Chain_Epoch_EpochDirection)(nil),           // 36: signal.proto.pq_ratchet.Chain.Epoch.EpochDirection
}
var file_pq_ratchet_proto_depIdxs = []int32{
	11, // 0: signal.proto.pq_ratchet.PqRatchetState.version_negotiation:type_name -> signal.proto.pq_ratchet.PqRatchetState.VersionNegotiation
	9,  // 1: signal.proto.pq_ratchet.PqRatchetState.chain:type_name -> signal.proto.pq_ratchet.Chain
	8,  // 2: signal.proto.pq_ratchet.PqRatchetState.v1:type_name -> signal.proto.pq_ratchet.V1State
	5,  // 3: signal.proto.pq_ratchet.V1Msg.hdr:type_name -> signal.proto.pq_ratchet.Chunk
	5,  // 4: signal.proto.pq_ratchet.V1Msg.ek:type_name -> signal.proto.pq_ratchet.Chunk
	5,  // 5: signal.proto.pq_ratchet.V1Msg.ek_ct1_ack:type_name -> signal.proto.pq_ratchet.Chunk
	5,  // 6: signal.proto.pq_ratchet.V1Msg.ct1:type_name -> signal.proto.pq_ratchet.Chunk
	5,  // 7: signal.proto.pq_ratchet.V1Msg.ct2:type_name -> signal.proto.pq_ratchet.Chunk
	24, // 8: signal.proto.pq_ratchet.V1State.keys_unsampled:type_name -> signal.proto.pq_ratchet.V1State.Chunked.KeysUnsampled
	25, // 9: signal.proto.pq_ratchet.V1State.keys_sampled:type_name -> signal.proto.pq_ratchet.V1State.Chunked.KeysSampled
	26, // 10: signal.proto.pq_ratchet.V1State.header_sent:type_name -> signal.proto.pq_ratchet.V1State.Chunked.HeaderSent
	27, // 11: signal.proto.pq_ratchet.V1State.ct1_received:type_name -> signal.proto.pq_ratchet.V1State.Chunked.Ct1Received
	28, // 12: signal.proto.pq_ratchet.V1State.ek_sent_ct1_received:type_name -> signal.proto.pq_ratchet.V1State.Chunked.EkSentCt1Received
	29, // 13: signal.proto.pq_ratchet.V1State.no_header_received:type_name -> signal.proto.pq_ratchet.V1State.Chunked.NoHeaderReceived
	30, // 14: signal.proto.pq_ratchet.V1State.header_received:type_name -> signal.proto.pq_ratchet.V1State.Chunked.HeaderReceived
	31, // 15: signal.proto.pq_ratchet.V1State.ct1_sampled:type_name -> signal.proto.pq_ratchet.V1State.Chunked.Ct1Sampled
	32, // 16: signal.proto.pq_ratchet.V1State.ek_received_ct1_sampled:type_name -> signal.proto.pq_ratchet.V1State.Chunked.EkReceivedCt1Sampled
	33, // 17: signal.proto.pq_ratchet.V1State.ct1_acknowledged:type_name -> signal.proto.pq_ratchet.V1State.Chunked.Ct1Acknowledged
	34, // 18: signal.proto.pq_ratchet.V1State.ct2_sampled:type_name -> signal.proto.pq_ratchet.V1State.Chunked.Ct2Sampled
	1,  // 19: signal.proto.pq_ratchet.Chain.direction:type_name -> signal.proto.pq_ratchet.Direction
	35, // 20: signal.proto.pq_ratchet.Chain.links:type_name -> signal.proto.pq_ratchet.Chain.Epoch
	10, // 21: signal.proto.pq_ratchet.Chain.params:type_name -> signal.proto.pq_ratchet.ChainParams
	1,  // 22: signal.proto.pq_ratchet.PqRatchetState.VersionNegotiation.direction:type_name -> signal.proto.pq_ratchet.Direction
	0,  // 23: signal.proto.pq_ratchet.PqRatchetState.VersionNegotiation.min_version:type_name -> signal.proto.pq_ratchet.Version
	10, // 24: signal.proto.pq_ratchet.PqRatchetState.VersionNegotiation.chain_params:type_name -> signal.proto.pq_ratchet.ChainParams
	7,  // 25: signal.proto.pq_ratchet.V1State.Unchunked.KeysUnsampled.auth:type_name -> signal.proto.pq_ratchet.Authenticator
	7,  // 26: signal.proto.pq_ratchet.V1State.Unchunked.HeaderSent.auth:type_name -> signal.proto.pq_ratchet.Authenticator
	7,  // 27: signal.proto.pq_ratchet.V1State.Unchunked.EkSent.auth:type_name -> signal.proto.pq_ratchet.Authenticator
	7,  // 28: signal.proto.pq_ratchet.V1State.Unchunked.EkSentCt1Received.auth:type_name -> signal.proto.pq_ratchet.Authenticator
	7,  // 29: signal.proto.pq_ratchet.V1State.Unchunked.NoHeaderReceived.auth:type_name -> signal.proto.pq_ratchet.Authenticator
	7,  // 30: signal.proto.pq_ratchet.V1State.Unchunked.HeaderReceived.auth:type_name -> signal.proto.pq_ratchet.Authenticator
	7,  // 31: signal.proto.pq_ratchet.V1State.Unchunked.EkReceived.auth:type_name -> signal.proto.pq_ratchet.Authenticator
	7,  // 32: signal.proto.pq_ratchet.V1State.Unchunked.Ct1Sent.auth:type_name -> signal.proto.pq_ratchet.Authenticator
	7,  // 33: signal.proto.pq_ratchet.V1State.Unchunked.Ct1SentEkReceived.auth:type_name -> signal.proto.pq_ratchet.Authenticator
	7,  // 34: signal.proto.pq_ratchet.V1State.Unchunked.Ct2Sent.auth:type_name -> signal.proto.pq_ratchet.Authenticator
	14, // 35: signal.proto.pq_ratchet.V1State.Chunked.KeysUnsampled.uc:type_name -> signal.proto.pq_ratchet.V1State.Unchunked.KeysUnsampled
	15, // 36: signal.proto.pq_ratchet.V1State.Chunked.KeysSampled.uc:type_name -> signal.proto.pq_ratchet.V1State.Unchunked.HeaderSent
	2,  // 37: signal.proto.pq_ratchet.V1State.Chunked.KeysSampled.sending_hdr:type_name -> signal.proto.pq_ratchet.PolynomialEncoder
	16, // 38: signal.proto.pq_ratchet.V1State.Chunked.HeaderSent.uc:type_name -> signal.proto.pq_ratchet.V1State.Unchunked.EkSent
	2,  // 39: signal.proto.pq_ratchet.V1State.Chunked.HeaderSent.sending_ek:type_name -> signal.proto.pq_ratchet.PolynomialEncoder
	3,  // 40: signal.proto.pq_ratchet.V1State.Chunked.HeaderSent.receiving_ct1:type_name -> signal.proto.pq_ratchet.PolynomialDecoder
	17, // 41: signal.proto.pq_ratchet.V1State.Chunked.Ct1Received.uc:type_name -> signal.proto.pq_ratchet.V1State.Unchunked.EkSentCt1Received
	2,  // 42: signal.proto.pq_ratchet.V1State.Chunked.Ct1Received.sending_ek:type_name -> signal.proto.pq_ratchet.PolynomialEncoder
	17, // 43: signal.proto.pq_ratchet.V1State.Chunked.EkSentCt1Received.uc:type_name -> signal.proto.pq_ratchet.V1State.Unchunked.EkSentCt1Received
	3,  // 44: signal.proto.pq_ratchet.V1State.Chunked.EkSentCt1Received.receiving_ct2:type_name -> signal.proto.pq_ratchet.PolynomialDecoder
	18, // 45: signal.proto.pq_ratchet.V1State.Chunked.NoHeaderReceived.uc:type_name -> signal.proto.pq_ratchet.V1State.Unchunked.NoHeaderReceived
	3,  // 46: signal.proto.pq_ratchet.V1State.Chunked.NoHeaderReceived.receiving_hdr:type_name -> signal.proto.pq_ratchet.PolynomialDecoder
	19, // 47: signal.proto.pq_ratchet.V1State.Chunked.HeaderReceived.uc:type_name -> signal.proto.pq_ratchet.V1State.Unchunked.HeaderReceived
	3,  // 48: signal.proto.pq_ratchet.V1State.Chunked.HeaderReceived.receiving_ek:type_name -> signal.proto.pq_ratchet.PolynomialDecoder
	21, // 49: signal.proto.pq_ratchet.V1State.Chunked.Ct1Sampled.uc:type_name -> signal.proto.pq_ratchet.V1State.Unchunked.Ct1Sent
	2,  // 50: signal.proto.pq_ratchet.V1State.Chunked.Ct1Sampled.sending_ct1:type_name -> signal.proto.pq_ratchet.PolynomialEncoder
	3,  // 51: signal.proto.pq_ratchet.V1State.Chunked.Ct1Sampled.receiving_ek:type_name -> signal.proto.pq_ratchet.PolynomialDecoder
	22, // 52: signal.proto.pq_ratchet.V1State.Chunked.EkReceivedCt1Sampled.uc:type_name -> signal.proto.pq_ratchet.V1State.Unchunked.Ct1SentEkReceived
	2,  // 53: signal.proto.pq_ratchet.V1State.Chunked.EkReceivedCt1Sampled.sending_ct1:type_name -> signal.proto.pq_ratchet.PolynomialEncoder
	21, // 54: signal.proto.pq_ratchet.V1State.Chunked.Ct1Acknowledged.uc:type_name -> signal.proto.pq_ratchet.V1State.Unchunked.Ct1Sent
	3,  // 55: signal.proto.pq_ratchet.V1State.Chunked.Ct1Acknowledged.receiving_ek:type_name -> signal.proto.pq_ratchet.PolynomialDecoder
	23, // 56: signal.proto.pq_ratchet.V1State.Chunked.Ct2Sampled.uc:type_name -> signal.proto.pq_ratchet.V1State.Unchunked.Ct2Sent
	2,  // 57: signal.proto.pq_ratchet.V1State.Chunked.Ct2Sampled.sending_ct2:type_name -> signal.proto.pq_ratchet.PolynomialEncoder
	36, // 58: signal.proto.pq_ratchet.Chain.Epoch.send:type_name -> signal.proto.pq_ratchet.Chain.Epoch.EpochDirection
	36, // 59: signal.proto.pq_ratchet.Chain.Epoch.recv:type_name -> signal.proto.pq_ratchet.Chain.Epoch.EpochDirection
	60, // [60:60] is the sub-list for method output_type
	60, // [60:60] is the sub-list for method input_type
	60, // [60:60] is the sub-list for extension type_name
	60, // [60:60] is the sub-list for extension extendee
	0,  // [0:60] is the sub-list for field type_name
}

func init() { file_pq_ratchet_proto_init() }
func file_pq_ratchet_proto_init() {
	if File_pq_ratchet_proto != nil {
		return
	}
	file_pq_ratchet_proto_msgTypes[2].OneofWrappers = []any{
		(*PqRatchetState_V1)(nil),
	}
	file_pq_ratchet_proto_msgTypes[4].OneofWrappers = []any{
		(*V1Msg_Hdr)(nil),
		(*V1Msg_Ek)(nil),
		(*V1Msg_EkCt1Ack)(nil),
		(*V1Msg_Ct1Ack)(nil),
		(*V1Msg_Ct1)(nil),
		(*V1Msg_Ct2)(nil),
	}
	file_pq_ratchet_proto_msgTypes[6].OneofWrappers = []any{
		(*V1State_KeysUnsampled)(nil),
		(*V1State_KeysSampled)(nil),
		(*V1State_HeaderSent)(nil),
		(*V1State_Ct1Received)(nil),
		(*V1State_EkSentCt1Received)(nil),
		(*V1State_NoHeaderReceived)(nil),
		(*V1State_HeaderReceived)(nil),
		(*V1State_Ct1Sampled)(nil),
		(*V1State_EkReceivedCt1Sampled)(nil),
		(*V1State_Ct1Acknowledged)(nil),
		(*V1State_Ct2Sampled)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pq_ratchet_proto_rawDesc), len(file_pq_ratchet_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pq_ratchet_proto_goTypes,
		DependencyIndexes: file_pq_ratchet_proto_depIdxs,
		EnumInfos:         file_pq_ratchet_proto_enumTypes,
		MessageInfos:      file_pq_ratchet_proto_msgTypes,
	}.Build()
	File_pq_ratchet_proto = out.File
	file_pq_ratchet_proto_goTypes = nil
	file_pq_ratchet_proto_depIdxs = nil
}
