// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: sealed_sender.proto

//
// Copyright 2020 Signal Messenger, LLC.
// SPDX-License-Identifier: AGPL-3.0-only
//

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnidentifiedSenderMessage_Message_Type int32

const (
	UnidentifiedSenderMessage_Message_PREKEY_MESSAGE    UnidentifiedSenderMessage_Message_Type = 1
	UnidentifiedSenderMessage_Message_MESSAGE           UnidentifiedSenderMessage_Message_Type = 2
	UnidentifiedSenderMessage_Message_SENDERKEY_MESSAGE UnidentifiedSenderMessage_Message_Type = 7
	UnidentifiedSenderMessage_Message_PLAINTEXT_CONTENT UnidentifiedSenderMessage_Message_Type = 8
)

// Enum value maps for UnidentifiedSenderMessage_Message_Type.
var (
	UnidentifiedSenderMessage_Message_Type_name = map[int32]string{
		1: "PREKEY_MESSAGE",
		2: "MESSAGE",
		7: "SENDERKEY_MESSAGE",
		8: "PLAINTEXT_CONTENT",
	}
	UnidentifiedSenderMessage_Message_Type_value = map[string]int32{
		"PREKEY_MESSAGE":    1,
		"MESSAGE":           2,
		"SENDERKEY_MESSAGE": 7,
		"PLAINTEXT_CONTENT": 8,
	}
)

func (x UnidentifiedSenderMessage_Message_Type) Enum() *UnidentifiedSenderMessage_Message_Type {
	p := new(UnidentifiedSenderMessage_Message_Type)
	*p = x
	return p
}

func (x UnidentifiedSenderMessage_Message_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnidentifiedSenderMessage_Message_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_sealed_sender_proto_enumTypes[0].Descriptor()
}

func (UnidentifiedSenderMessage_Message_Type) Type() protoreflect.EnumType {
	return &file_sealed_sender_proto_enumTypes[0]
}

func (x UnidentifiedSenderMessage_Message_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *UnidentifiedSenderMessage_Message_Type) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = UnidentifiedSenderMessage_Message_Type(num)
	return nil
}

// Deprecated: Use UnidentifiedSenderMessage_Message_Type.Descriptor instead.
func (UnidentifiedSenderMessage_Message_Type) EnumDescriptor() ([]byte, []int) {
	return file_sealed_sender_proto_rawDescGZIP(), []int{2, 0, 0}
}

type UnidentifiedSenderMessage_Message_ContentHint int32

const (
	UnidentifiedSenderMessage_Message_RESENDABLE UnidentifiedSenderMessage_Message_ContentHint = 1 // Sender will try to resend; delay any error UI if possible
	UnidentifiedSenderMessage_Message_IMPLICIT   UnidentifiedSenderMessage_Message_ContentHint = 2 // Don't show any error UI at all; this is something sent implicitly like a typing message or a receipt
)

// Enum value maps for UnidentifiedSenderMessage_Message_ContentHint.
var (
	UnidentifiedSenderMessage_Message_ContentHint_name = map[int32]string{
		1: "RESENDABLE",
		2: "IMPLICIT",
	}
	UnidentifiedSenderMessage_Message_ContentHint_value = map[string]int32{
		"RESENDABLE": 1,
		"IMPLICIT":   2,
	}
)

func (x UnidentifiedSenderMessage_Message_ContentHint) Enum() *UnidentifiedSenderMessage_Message_ContentHint {
	p := new(UnidentifiedSenderMessage_Message_ContentHint)
	*p = x
	return p
}

func (x UnidentifiedSenderMessage_Message_ContentHint) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnidentifiedSenderMessage_Message_ContentHint) Descriptor() protoreflect.EnumDescriptor {
	return file_sealed_sender_proto_enumTypes[1].Descriptor()
}

func (UnidentifiedSenderMessage_Message_ContentHint) Type() protoreflect.EnumType {
	return &file_sealed_sender_proto_enumTypes[1]
}

func (x UnidentifiedSenderMessage_Message_ContentHint) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *UnidentifiedSenderMessage_Message_ContentHint) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = UnidentifiedSenderMessage_Message_ContentHint(num)
	return nil
}

// Deprecated: Use UnidentifiedSenderMessage_Message_ContentHint.Descriptor instead.
func (UnidentifiedSenderMessage_Message_ContentHint) EnumDescriptor() ([]byte, []int) {
	return file_sealed_sender_proto_rawDescGZIP(), []int{2, 0, 1}
}

type ServerCertificate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   []byte                 `protobuf:"bytes,1,opt,name=certificate" json:"certificate,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCertificate) Reset() {
	*x = ServerCertificate{}
	mi := &file_sealed_sender_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCertificate) ProtoMessage() {}

func (x *ServerCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_sealed_sender_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCertificate.ProtoReflect.Descriptor instead.
func (*ServerCertificate) Descriptor() ([]byte, []int) {
	return file_sealed_sender_proto_rawDescGZIP(), []int{0}
}

func (x *ServerCertificate) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *ServerCertificate) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type SenderCertificate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   []byte                 `protobuf:"bytes,1,opt,name=certificate" json:"certificate,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SenderCertificate) Reset() {
	*x = SenderCertificate{}
	mi := &file_sealed_sender_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SenderCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderCertificate) ProtoMessage() {}

func (x *SenderCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_sealed_sender_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderCertificate.ProtoReflect.Descriptor instead.
func (*SenderCertificate) Descriptor() ([]byte, []int) {
	return file_sealed_sender_proto_rawDescGZIP(), []int{1}
}

func (x *SenderCertificate) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *SenderCertificate) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type UnidentifiedSenderMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EphemeralPublic  []byte                 `protobuf:"bytes,1,opt,name=ephemeralPublic" json:"ephemeralPublic,omitempty"`
	EncryptedStatic  []byte                 `protobuf:"bytes,2,opt,name=encryptedStatic" json:"encryptedStatic,omitempty"`
	EncryptedMessage []byte                 `protobuf:"bytes,3,opt,name=encryptedMessage" json:"encryptedMessage,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UnidentifiedSenderMessage) Reset() {
	*x = UnidentifiedSenderMessage{}
	mi := &file_sealed_sender_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnidentifiedSenderMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnidentifiedSenderMessage) ProtoMessage() {}

func (x *UnidentifiedSenderMessage) ProtoReflect() protoreflect.Message {
	mi := &file_sealed_sender_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnidentifiedSenderMessage.ProtoReflect.Descriptor instead.
func (*UnidentifiedSenderMessage) Descriptor() ([]byte, []int) {
	return file_sealed_sender_proto_rawDescGZIP(), []int{2}
}

func (x *UnidentifiedSenderMessage) GetEphemeralPublic() []byte {
	if x != nil {
		return x.EphemeralPublic
	}
	return nil
}

func (x *UnidentifiedSenderMessage) GetEncryptedStatic() []byte {
	if x != nil {
		return x.EncryptedStatic
	}
	return nil
}

func (x *UnidentifiedSenderMessage) GetEncryptedMessage() []byte {
	if x != nil {
		return x.EncryptedMessage
	}
	return nil
}

type ServerCertificate_Certificate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCertificate_Certificate) Reset() {
	*x = ServerCertificate_Certificate{}
	mi := &file_sealed_sender_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCertificate_Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCertificate_Certificate) ProtoMessage() {}

func (x *ServerCertificate_Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_sealed_sender_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCertificate_Certificate.ProtoReflect.Descriptor instead.
func (*ServerCertificate_Certificate) Descriptor() ([]byte, []int) {
	return file_sealed_sender_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ServerCertificate_Certificate) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *ServerCertificate_Certificate) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type SenderCertificate_Certificate struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SenderE164 *string                `protobuf:"bytes,1,opt,name=senderE164" json:"senderE164,omitempty"`
	// Types that are valid to be assigned to SenderUuid:
	//
	//	*SenderCertificate_Certificate_UuidString
	//	*SenderCertificate_Certificate_UuidBytes
	SenderUuid   isSenderCertificate_Certificate_SenderUuid `protobuf_oneof:"senderUuid"`
	SenderDevice *uint32                                    `protobuf:"varint,2,opt,name=senderDevice" json:"senderDevice,omitempty"`
	Expires      *uint64                                    `protobuf:"fixed64,3,opt,name=expires" json:"expires,omitempty"`
	IdentityKey  []byte                                     `protobuf:"bytes,4,opt,name=identityKey" json:"identityKey,omitempty"`
	// Types that are valid to be assigned to Signer:
	//
	//	*SenderCertificate_Certificate_Certificate
	//	*SenderCertificate_Certificate_Id
	Signer        isSenderCertificate_Certificate_Signer `protobuf_oneof:"signer"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SenderCertificate_Certificate) Reset() {
	*x = SenderCertificate_Certificate{}
	mi := &file_sealed_sender_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SenderCertificate_Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderCertificate_Certificate) ProtoMessage() {}

func (x *SenderCertificate_Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_sealed_sender_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderCertificate_Certificate.ProtoReflect.Descriptor instead.
func (*SenderCertificate_Certificate) Descriptor() ([]byte, []int) {
	return file_sealed_sender_proto_rawDescGZIP(), []int{1, 0}
}

func (x *SenderCertificate_Certificate) GetSenderE164() string {
	if x != nil && x.SenderE164 != nil {
		return *x.SenderE164
	}
	return ""
}

func (x *SenderCertificate_Certificate) GetSenderUuid() isSenderCertificate_Certificate_SenderUuid {
	if x != nil {
		return x.SenderUuid
	}
	return nil
}

func (x *SenderCertificate_Certificate) GetUuidString() string {
	if x != nil {
		if x, ok := x.SenderUuid.(*SenderCertificate_Certificate_UuidString); ok {
			return x.UuidString
		}
	}
	return ""
}

func (x *SenderCertificate_Certificate) GetUuidBytes() []byte {
	if x != nil {
		if x, ok := x.SenderUuid.(*SenderCertificate_Certificate_UuidBytes); ok {
			return x.UuidBytes
		}
	}
	return nil
}

func (x *SenderCertificate_Certificate) GetSenderDevice() uint32 {
	if x != nil && x.SenderDevice != nil {
		return *x.SenderDevice
	}
	return 0
}

func (x *SenderCertificate_Certificate) GetExpires() uint64 {
	if x != nil && x.Expires != nil {
		return *x.Expires
	}
	return 0
}

func (x *SenderCertificate_Certificate) GetIdentityKey() []byte {
	if x != nil {
		return x.IdentityKey
	}
	return nil
}

func (x *SenderCertificate_Certificate) GetSigner() isSenderCertificate_Certificate_Signer {
	if x != nil {
		return x.Signer
	}
	return nil
}

func (x *SenderCertificate_Certificate) GetCertificate() []byte {
	if x != nil {
		if x, ok := x.Signer.(*SenderCertificate_Certificate_Certificate); ok {
			return x.Certificate
		}
	}
	return nil
}

func (x *SenderCertificate_Certificate) GetId() uint32 {
	if x != nil {
		if x, ok := x.Signer.(*SenderCertificate_Certificate_Id); ok {
			return x.Id
		}
	}
	return 0
}

type isSenderCertificate_Certificate_SenderUuid interface {
	isSenderCertificate_Certificate_SenderUuid()
}

type SenderCertificate_Certificate_UuidString struct {
	UuidString string `protobuf:"bytes,6,opt,name=uuidString,oneof"`
}

type SenderCertificate_Certificate_UuidBytes struct {
	UuidBytes []byte `protobuf:"bytes,7,opt,name=uuidBytes,oneof"`
}

func (*SenderCertificate_Certificate_UuidString) isSenderCertificate_Certificate_SenderUuid() {}

func (*SenderCertificate_Certificate_UuidBytes) isSenderCertificate_Certificate_SenderUuid() {}

type isSenderCertificate_Certificate_Signer interface {
	isSenderCertificate_Certificate_Signer()
}

type SenderCertificate_Certificate_Certificate struct {
	Certificate []byte `protobuf:"bytes,5,opt,name=certificate,oneof"`
}

type SenderCertificate_Certificate_Id struct {
	Id uint32 `protobuf:"varint,8,opt,name=id,oneof"`
}

func (*SenderCertificate_Certificate_Certificate) isSenderCertificate_Certificate_Signer() {}

func (*SenderCertificate_Certificate_Id) isSenderCertificate_Certificate_Signer() {}

type UnidentifiedSenderMessage_Message struct {
	state             protoimpl.MessageState                         `protogen:"open.v1"`
	Type              *UnidentifiedSenderMessage_Message_Type        `protobuf:"varint,1,opt,name=type,enum=signal.proto.sealed_sender.UnidentifiedSenderMessage_Message_Type" json:"type,omitempty"`
	SenderCertificate []byte                                         `protobuf:"bytes,2,opt,name=senderCertificate" json:"senderCertificate,omitempty"`
	Content           []byte                                         `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
	ContentHint       *UnidentifiedSenderMessage_Message_ContentHint `protobuf:"varint,4,opt,name=contentHint,enum=signal.proto.sealed_sender.UnidentifiedSenderMessage_Message_ContentHint" json:"contentHint,omitempty"`
	GroupId           []byte                                         `protobuf:"bytes,5,opt,name=groupId" json:"groupId,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UnidentifiedSenderMessage_Message) Reset() {
	*x = UnidentifiedSenderMessage_Message{}
	mi := &file_sealed_sender_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnidentifiedSenderMessage_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnidentifiedSenderMessage_Message) ProtoMessage() {}

func (x *UnidentifiedSenderMessage_Message) ProtoReflect() protoreflect.Message {
	mi := &file_sealed_sender_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnidentifiedSenderMessage_Message.ProtoReflect.Descriptor instead.
func (*UnidentifiedSenderMessage_Message) Descriptor() ([]byte, []int) {
	return file_sealed_sender_proto_rawDescGZIP(), []int{2, 0}
}

func (x *UnidentifiedSenderMessage_Message) GetType() UnidentifiedSenderMessage_Message_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return UnidentifiedSenderMessage_Message_PREKEY_MESSAGE
}

func (x *UnidentifiedSenderMessage_Message) GetSenderCertificate() []byte {
	if x != nil {
		return x.SenderCertificate
	}
	return nil
}

func (x *UnidentifiedSenderMessage_Message) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UnidentifiedSenderMessage_Message) GetContentHint() UnidentifiedSenderMessage_Message_ContentHint {
	if x != nil && x.ContentHint != nil {
		return *x.ContentHint
	}
	return UnidentifiedSenderMessage_Message_RESENDABLE
}

func (x *UnidentifiedSenderMessage_Message) GetGroupId() []byte {
	if x != nil {
		return x.GroupId
	}
	return nil
}

var File_sealed_sender_proto protoreflect.FileDescriptor

const file_sealed_sender_proto_rawDesc = "" +
	"\n" +
	"\x13sealed_sender.proto\x12\x1asignal.proto.sealed_sender\"\x84\x01\n" +
	"\x11ServerCertificate\x12 \n" +
	"\vcertificate\x18\x01 \x01(\fR\vcertificate\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x1a/\n" +
	"\vCertificate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"\xf3\x02\n" +
	"\x11SenderCertificate\x12 \n" +
	"\vcertificate\x18\x01 \x01(\fR\vcertificate\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x1a\x9d\x02\n" +
	"\vCertificate\x12\x1e\n" +
	"\n" +
	"senderE164\x18\x01 \x01(\tR\n" +
	"senderE164\x12 \n" +
	"\n" +
	"uuidString\x18\x06 \x01(\tH\x00R\n" +
	"uuidString\x12\x1e\n" +
	"\tuuidBytes\x18\a \x01(\fH\x00R\tuuidBytes\x12\"\n" +
	"\fsenderDevice\x18\x02 \x01(\rR\fsenderDevice\x12\x18\n" +
	"\aexpires\x18\x03 \x01(\x06R\aexpires\x12 \n" +
	"\videntityKey\x18\x04 \x01(\fR\videntityKey\x12\"\n" +
	"\vcertificate\x18\x05 \x01(\fH\x01R\vcertificate\x12\x10\n" +
	"\x02id\x18\b \x01(\rH\x01R\x02idB\f\n" +
	"\n" +
	"senderUuidB\b\n" +
	"\x06signer\"\xde\x04\n" +
	"\x19UnidentifiedSenderMessage\x12(\n" +
	"\x0fephemeralPublic\x18\x01 \x01(\fR\x0fephemeralPublic\x12(\n" +
	"\x0fencryptedStatic\x18\x02 \x01(\fR\x0fencryptedStatic\x12*\n" +
	"\x10encryptedMessage\x18\x03 \x01(\fR\x10encryptedMessage\x1a\xc0\x03\n" +
	"\aMessage\x12V\n" +
	"\x04type\x18\x01 \x01(\x0e2B.signal.proto.sealed_sender.UnidentifiedSenderMessage.Message.TypeR\x04type\x12,\n" +
	"\x11senderCertificate\x18\x02 \x01(\fR\x11senderCertificate\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12k\n" +
	"\vcontentHint\x18\x04 \x01(\x0e2I.signal.proto.sealed_sender.UnidentifiedSenderMessage.Message.ContentHintR\vcontentHint\x12\x18\n" +
	"\agroupId\x18\x05 \x01(\fR\agroupId\"[\n" +
	"\x04Type\x12\x12\n" +
	"\x0ePREKEY_MESSAGE\x10\x01\x12\v\n" +
	"\aMESSAGE\x10\x02\x12\x15\n" +
	"\x11SENDERKEY_MESSAGE\x10\a\x12\x15\n" +
	"\x11PLAINTEXT_CONTENT\x10\b\"\x04\b\x03\x10\x06\"1\n" +
	"\vContentHint\x12\x0e\n" +
	"\n" +
	"RESENDABLE\x10\x01\x12\f\n" +
	"\bIMPLICIT\x10\x02\"\x04\b\x00\x10\x00B+Z)github.com/GoCodeAlone/libsignal-go/proto"

var (
	file_sealed_sender_proto_rawDescOnce sync.Once
	file_sealed_sender_proto_rawDescData []byte
)

func file_sealed_sender_proto_rawDescGZIP() []byte {
	file_sealed_sender_proto_rawDescOnce.Do(func() {
		file_sealed_sender_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sealed_sender_proto_rawDesc), len(file_sealed_sender_proto_rawDesc)))
	})
	return file_sealed_sender_proto_rawDescData
}

var file_sealed_sender_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sealed_sender_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sealed_sender_proto_goTypes = []any{
	(UnidentifiedSenderMessage_Message_Type)(0),        // 0: signal.proto.sealed_sender.UnidentifiedSenderMessage.Message.Type
	(UnidentifiedSenderMessage_Message_ContentHint)(0), // 1: signal.proto.sealed_sender.UnidentifiedSenderMessage.Message.ContentHint
	(*ServerCertificate)(nil),                          // 2: signal.proto.sealed_sender.ServerCertificate
	(*SenderCertificate)(nil),                          // 3: signal.proto.sealed_sender.SenderCertificate
	(*UnidentifiedSenderMessage)(nil),                  // 4: signal.proto.sealed_sender.UnidentifiedSenderMessage
	(*ServerCertificate_Certificate)(nil),              // 5: signal.proto.sealed_sender.ServerCertificate.Certificate
	(*SenderCertificate_Certificate)(nil),              // 6: signal.proto.sealed_sender.SenderCertificate.Certificate
	(*UnidentifiedSenderMessage_Message)(nil),          // 7: signal.proto.sealed_sender.UnidentifiedSenderMessage.Message
}
var file_sealed_sender_proto_depIdxs = []int32{
	0, // 0: signal.proto.sealed_sender.UnidentifiedSenderMessage.Message.type:type_name -> signal.proto.sealed_sender.UnidentifiedSenderMessage.Message.Type
	1, // 1: signal.proto.sealed_sender.UnidentifiedSenderMessage.Message.contentHint:type_name -> signal.proto.sealed_sender.UnidentifiedSenderMessage.Message.ContentHint
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sealed_sender_proto_init() }
func file_sealed_sender_proto_init() {
	if File_sealed_sender_proto != nil {
		return
	}
	file_sealed_sender_proto_msgTypes[4].OneofWrappers = []any{
		(*SenderCertificate_Certificate_UuidString)(nil),
		(*SenderCertificate_Certificate_UuidBytes)(nil),
		(*SenderCertificate_Certificate_Certificate)(nil),
		(*SenderCertificate_Certificate_Id)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sealed_sender_proto_rawDesc), len(file_sealed_sender_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sealed_sender_proto_goTypes,
		DependencyIndexes: file_sealed_sender_proto_depIdxs,
		EnumInfos:         file_sealed_sender_proto_enumTypes,
		MessageInfos:      file_sealed_sender_proto_msgTypes,
	}.Build()
	File_sealed_sender_proto = out.File
	file_sealed_sender_proto_goTypes = nil
	file_sealed_sender_proto_depIdxs = nil
}
