//
// Copyright 2021 Signal Messenger, LLC.
// SPDX-License-Identifier: AGPL-3.0-only
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Content struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	DataMessage                  []byte                 `protobuf:"bytes,1,opt,name=data_message,json=dataMessage" json:"data_message,omitempty"`
	SyncMessage                  []byte                 `protobuf:"bytes,2,opt,name=sync_message,json=syncMessage" json:"sync_message,omitempty"`
	CallMessage                  []byte                 `protobuf:"bytes,3,opt,name=call_message,json=callMessage" json:"call_message,omitempty"`
	NullMessage                  []byte                 `protobuf:"bytes,4,opt,name=null_message,json=nullMessage" json:"null_message,omitempty"`
	ReceiptMessage               []byte                 `protobuf:"bytes,5,opt,name=receipt_message,json=receiptMessage" json:"receipt_message,omitempty"`
	TypingMessage                []byte                 `protobuf:"bytes,6,opt,name=typing_message,json=typingMessage" json:"typing_message,omitempty"`
	SenderKeyDistributionMessage []byte                 `protobuf:"bytes,7,opt,name=sender_key_distribution_message,json=senderKeyDistributionMessage" json:"sender_key_distribution_message,omitempty"`
	DecryptionErrorMessage       []byte                 `protobuf:"bytes,8,opt,name=decryption_error_message,json=decryptionErrorMessage" json:"decryption_error_message,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *Content) GetDataMessage() []byte {
	if x != nil {
		return x.DataMessage
	}
	return nil
}

func (x *Content) GetSyncMessage() []byte {
	if x != nil {
		return x.SyncMessage
	}
	return nil
}

func (x *Content) GetCallMessage() []byte {
	if x != nil {
		return x.CallMessage
	}
	return nil
}

func (x *Content) GetNullMessage() []byte {
	if x != nil {
		return x.NullMessage
	}
	return nil
}

func (x *Content) GetReceiptMessage() []byte {
	if x != nil {
		return x.ReceiptMessage
	}
	return nil
}

func (x *Content) GetTypingMessage() []byte {
	if x != nil {
		return x.TypingMessage
	}
	return nil
}

func (x *Content) GetSenderKeyDistributionMessage() []byte {
	if x != nil {
		return x.SenderKeyDistributionMessage
	}
	return nil
}

func (x *Content) GetDecryptionErrorMessage() []byte {
	if x != nil {
		return x.DecryptionErrorMessage
	}
	return nil
}

type DecryptionErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RatchetKey    []byte                 `protobuf:"bytes,1,opt,name=ratchet_key,json=ratchetKey" json:"ratchet_key,omitempty"` // set to the public ratchet key from the SignalMessage if a 1-1 payload fails to decrypt
	Timestamp     *uint64                `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	DeviceId      *uint32                `protobuf:"varint,3,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptionErrorMessage) Reset() {
	*x = DecryptionErrorMessage{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptionErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptionErrorMessage) ProtoMessage() {}

func (x *DecryptionErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptionErrorMessage.ProtoReflect.Descriptor instead.
func (*DecryptionErrorMessage) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *DecryptionErrorMessage) GetRatchetKey() []byte {
	if x != nil {
		return x.RatchetKey
	}
	return nil
}

func (x *DecryptionErrorMessage) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *DecryptionErrorMessage) GetDeviceId() uint32 {
	if x != nil && x.DeviceId != nil {
		return *x.DeviceId
	}
	return 0
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\rsignalservice\"\xe6\x02\n" +
	"\aContent\x12!\n" +
	"\fdata_message\x18\x01 \x01(\fR\vdataMessage\x12!\n" +
	"\fsync_message\x18\x02 \x01(\fR\vsyncMessage\x12!\n" +
	"\fcall_message\x18\x03 \x01(\fR\vcallMessage\x12!\n" +
	"\fnull_message\x18\x04 \x01(\fR\vnullMessage\x12'\n" +
	"\x0freceipt_message\x18\x05 \x01(\fR\x0ereceiptMessage\x12%\n" +
	"\x0etyping_message\x18\x06 \x01(\fR\rtypingMessage\x12E\n" +
	"\x1fsender_key_distribution_message\x18\a \x01(\fR\x1csenderKeyDistributionMessage\x128\n" +
	"\x18decryption_error_message\x18\b \x01(\fR\x16decryptionErrorMessage\"t\n" +
	"\x16DecryptionErrorMessage\x12\x1f\n" +
	"\vratchet_key\x18\x01 \x01(\fR\n" +
	"ratchetKey\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\rR\bdeviceIdB+Z)github.com/GoCodeAlone/libsignal-go/proto"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_proto_goTypes = []any{
	(*Content)(nil),                // 0: signalservice.Content
	(*DecryptionErrorMessage)(nil), // 1: signalservice.DecryptionErrorMessage
}
var file_service_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
