// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: storage.proto

//
// Copyright 2020 Signal Messenger, LLC.
// SPDX-License-Identifier: AGPL-3.0-only
//

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionStructure struct {
	state                protoimpl.MessageState  `protogen:"open.v1"`
	SessionVersion       uint32                  `protobuf:"varint,1,opt,name=session_version,json=sessionVersion,proto3" json:"session_version,omitempty"`
	LocalIdentityPublic  []byte                  `protobuf:"bytes,2,opt,name=local_identity_public,json=localIdentityPublic,proto3" json:"local_identity_public,omitempty"`
	RemoteIdentityPublic []byte                  `protobuf:"bytes,3,opt,name=remote_identity_public,json=remoteIdentityPublic,proto3" json:"remote_identity_public,omitempty"`
	RootKey              []byte                  `protobuf:"bytes,4,opt,name=root_key,json=rootKey,proto3" json:"root_key,omitempty"`
	PreviousCounter      uint32                  `protobuf:"varint,5,opt,name=previous_counter,json=previousCounter,proto3" json:"previous_counter,omitempty"`
	SenderChain          *SessionStructure_Chain `protobuf:"bytes,6,opt,name=sender_chain,json=senderChain,proto3" json:"sender_chain,omitempty"`
	// The order is significant; keys at the end are "older" and will get trimmed.
	ReceiverChains       []*SessionStructure_Chain            `protobuf:"bytes,7,rep,name=receiver_chains,json=receiverChains,proto3" json:"receiver_chains,omitempty"`
	PendingPreKey        *SessionStructure_PendingPreKey      `protobuf:"bytes,9,opt,name=pending_pre_key,json=pendingPreKey,proto3" json:"pending_pre_key,omitempty"`
	PendingKyberPreKey   *SessionStructure_PendingKyberPreKey `protobuf:"bytes,14,opt,name=pending_kyber_pre_key,json=pendingKyberPreKey,proto3" json:"pending_kyber_pre_key,omitempty"`
	RemoteRegistrationId uint32                               `protobuf:"varint,10,opt,name=remote_registration_id,json=remoteRegistrationId,proto3" json:"remote_registration_id,omitempty"`
	LocalRegistrationId  uint32                               `protobuf:"varint,11,opt,name=local_registration_id,json=localRegistrationId,proto3" json:"local_registration_id,omitempty"`
	AliceBaseKey         []byte                               `protobuf:"bytes,13,opt,name=alice_base_key,json=aliceBaseKey,proto3" json:"alice_base_key,omitempty"`
	PqRatchetState       []byte                               `protobuf:"bytes,15,opt,name=pq_ratchet_state,json=pqRatchetState,proto3" json:"pq_ratchet_state,omitempty"` // Next index: 16
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SessionStructure) Reset() {
	*x = SessionStructure{}
	mi := &file_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStructure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStructure) ProtoMessage() {}

func (x *SessionStructure) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStructure.ProtoReflect.Descriptor instead.
func (*SessionStructure) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

func (x *SessionStructure) GetSessionVersion() uint32 {
	if x != nil {
		return x.SessionVersion
	}
	return 0
}

func (x *SessionStructure) GetLocalIdentityPublic() []byte {
	if x != nil {
		return x.LocalIdentityPublic
	}
	return nil
}

func (x *SessionStructure) GetRemoteIdentityPublic() []byte {
	if x != nil {
		return x.RemoteIdentityPublic
	}
	return nil
}

func (x *SessionStructure) GetRootKey() []byte {
	if x != nil {
		return x.RootKey
	}
	return nil
}

func (x *SessionStructure) GetPreviousCounter() uint32 {
	if x != nil {
		return x.PreviousCounter
	}
	return 0
}

func (x *SessionStructure) GetSenderChain() *SessionStructure_Chain {
	if x != nil {
		return x.SenderChain
	}
	return nil
}

func (x *SessionStructure) GetReceiverChains() []*SessionStructure_Chain {
	if x != nil {
		return x.ReceiverChains
	}
	return nil
}

func (x *SessionStructure) GetPendingPreKey() *SessionStructure_PendingPreKey {
	if x != nil {
		return x.PendingPreKey
	}
	return nil
}

func (x *SessionStructure) GetPendingKyberPreKey() *SessionStructure_PendingKyberPreKey {
	if x != nil {
		return x.PendingKyberPreKey
	}
	return nil
}

func (x *SessionStructure) GetRemoteRegistrationId() uint32 {
	if x != nil {
		return x.RemoteRegistrationId
	}
	return 0
}

func (x *SessionStructure) GetLocalRegistrationId() uint32 {
	if x != nil {
		return x.LocalRegistrationId
	}
	return 0
}

func (x *SessionStructure) GetAliceBaseKey() []byte {
	if x != nil {
		return x.AliceBaseKey
	}
	return nil
}

func (x *SessionStructure) GetPqRatchetState() []byte {
	if x != nil {
		return x.PqRatchetState
	}
	return nil
}

type RecordStructure struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CurrentSession *SessionStructure      `protobuf:"bytes,1,opt,name=current_session,json=currentSession,proto3" json:"current_session,omitempty"`
	// The order is significant; sessions at the end are "older" and will get trimmed.
	PreviousSessions [][]byte `protobuf:"bytes,2,rep,name=previous_sessions,json=previousSessions,proto3" json:"previous_sessions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RecordStructure) Reset() {
	*x = RecordStructure{}
	mi := &file_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordStructure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordStructure) ProtoMessage() {}

func (x *RecordStructure) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordStructure.ProtoReflect.Descriptor instead.
func (*RecordStructure) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{1}
}

func (x *RecordStructure) GetCurrentSession() *SessionStructure {
	if x != nil {
		return x.CurrentSession
	}
	return nil
}

func (x *RecordStructure) GetPreviousSessions() [][]byte {
	if x != nil {
		return x.PreviousSessions
	}
	return nil
}

type PreKeyRecordStructure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PrivateKey    []byte                 `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreKeyRecordStructure) Reset() {
	*x = PreKeyRecordStructure{}
	mi := &file_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreKeyRecordStructure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreKeyRecordStructure) ProtoMessage() {}

func (x *PreKeyRecordStructure) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreKeyRecordStructure.ProtoReflect.Descriptor instead.
func (*PreKeyRecordStructure) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{2}
}

func (x *PreKeyRecordStructure) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PreKeyRecordStructure) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *PreKeyRecordStructure) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

type SignedPreKeyRecordStructure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PrivateKey    []byte                 `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	Timestamp     uint64                 `protobuf:"fixed64,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedPreKeyRecordStructure) Reset() {
	*x = SignedPreKeyRecordStructure{}
	mi := &file_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedPreKeyRecordStructure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedPreKeyRecordStructure) ProtoMessage() {}

func (x *SignedPreKeyRecordStructure) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedPreKeyRecordStructure.ProtoReflect.Descriptor instead.
func (*SignedPreKeyRecordStructure) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{3}
}

func (x *SignedPreKeyRecordStructure) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SignedPreKeyRecordStructure) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *SignedPreKeyRecordStructure) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *SignedPreKeyRecordStructure) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignedPreKeyRecordStructure) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type IdentityKeyPairStructure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PrivateKey    []byte                 `protobuf:"bytes,2,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityKeyPairStructure) Reset() {
	*x = IdentityKeyPairStructure{}
	mi := &file_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityKeyPairStructure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityKeyPairStructure) ProtoMessage() {}

func (x *IdentityKeyPairStructure) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityKeyPairStructure.ProtoReflect.Descriptor instead.
func (*IdentityKeyPairStructure) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{4}
}

func (x *IdentityKeyPairStructure) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *IdentityKeyPairStructure) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

type SenderKeyStateStructure struct {
	state             protoimpl.MessageState                      `protogen:"open.v1"`
	MessageVersion    uint32                                      `protobuf:"varint,5,opt,name=message_version,json=messageVersion,proto3" json:"message_version,omitempty"`
	ChainId           uint32                                      `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	SenderChainKey    *SenderKeyStateStructure_SenderChainKey     `protobuf:"bytes,2,opt,name=sender_chain_key,json=senderChainKey,proto3" json:"sender_chain_key,omitempty"`
	SenderSigningKey  *SenderKeyStateStructure_SenderSigningKey   `protobuf:"bytes,3,opt,name=sender_signing_key,json=senderSigningKey,proto3" json:"sender_signing_key,omitempty"`
	SenderMessageKeys []*SenderKeyStateStructure_SenderMessageKey `protobuf:"bytes,4,rep,name=sender_message_keys,json=senderMessageKeys,proto3" json:"sender_message_keys,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SenderKeyStateStructure) Reset() {
	*x = SenderKeyStateStructure{}
	mi := &file_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SenderKeyStateStructure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderKeyStateStructure) ProtoMessage() {}

func (x *SenderKeyStateStructure) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderKeyStateStructure.ProtoReflect.Descriptor instead.
func (*SenderKeyStateStructure) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{5}
}

func (x *SenderKeyStateStructure) GetMessageVersion() uint32 {
	if x != nil {
		return x.MessageVersion
	}
	return 0
}

func (x *SenderKeyStateStructure) GetChainId() uint32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *SenderKeyStateStructure) GetSenderChainKey() *SenderKeyStateStructure_SenderChainKey {
	if x != nil {
		return x.SenderChainKey
	}
	return nil
}

func (x *SenderKeyStateStructure) GetSenderSigningKey() *SenderKeyStateStructure_SenderSigningKey {
	if x != nil {
		return x.SenderSigningKey
	}
	return nil
}

func (x *SenderKeyStateStructure) GetSenderMessageKeys() []*SenderKeyStateStructure_SenderMessageKey {
	if x != nil {
		return x.SenderMessageKeys
	}
	return nil
}

type SenderKeyRecordStructure struct {
	state           protoimpl.MessageState     `protogen:"open.v1"`
	SenderKeyStates []*SenderKeyStateStructure `protobuf:"bytes,1,rep,name=sender_key_states,json=senderKeyStates,proto3" json:"sender_key_states,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SenderKeyRecordStructure) Reset() {
	*x = SenderKeyRecordStructure{}
	mi := &file_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SenderKeyRecordStructure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderKeyRecordStructure) ProtoMessage() {}

func (x *SenderKeyRecordStructure) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderKeyRecordStructure.ProtoReflect.Descriptor instead.
func (*SenderKeyRecordStructure) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{6}
}

func (x *SenderKeyRecordStructure) GetSenderKeyStates() []*SenderKeyStateStructure {
	if x != nil {
		return x.SenderKeyStates
	}
	return nil
}

type SessionStructure_Chain struct {
	state                   protoimpl.MessageState               `protogen:"open.v1"`
	SenderRatchetKey        []byte                               `protobuf:"bytes,1,opt,name=sender_ratchet_key,json=senderRatchetKey,proto3" json:"sender_ratchet_key,omitempty"`
	SenderRatchetKeyPrivate []byte                               `protobuf:"bytes,2,opt,name=sender_ratchet_key_private,json=senderRatchetKeyPrivate,proto3" json:"sender_ratchet_key_private,omitempty"`
	ChainKey                *SessionStructure_Chain_ChainKey     `protobuf:"bytes,3,opt,name=chain_key,json=chainKey,proto3" json:"chain_key,omitempty"`
	MessageKeys             []*SessionStructure_Chain_MessageKey `protobuf:"bytes,4,rep,name=message_keys,json=messageKeys,proto3" json:"message_keys,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SessionStructure_Chain) Reset() {
	*x = SessionStructure_Chain{}
	mi := &file_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStructure_Chain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStructure_Chain) ProtoMessage() {}

func (x *SessionStructure_Chain) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStructure_Chain.ProtoReflect.Descriptor instead.
func (*SessionStructure_Chain) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SessionStructure_Chain) GetSenderRatchetKey() []byte {
	if x != nil {
		return x.SenderRatchetKey
	}
	return nil
}

func (x *SessionStructure_Chain) GetSenderRatchetKeyPrivate() []byte {
	if x != nil {
		return x.SenderRatchetKeyPrivate
	}
	return nil
}

func (x *SessionStructure_Chain) GetChainKey() *SessionStructure_Chain_ChainKey {
	if x != nil {
		return x.ChainKey
	}
	return nil
}

func (x *SessionStructure_Chain) GetMessageKeys() []*SessionStructure_Chain_MessageKey {
	if x != nil {
		return x.MessageKeys
	}
	return nil
}

type SessionStructure_PendingPreKey struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PreKeyId       *uint32                `protobuf:"varint,1,opt,name=pre_key_id,json=preKeyId,proto3,oneof" json:"pre_key_id,omitempty"`
	SignedPreKeyId int32                  `protobuf:"varint,3,opt,name=signed_pre_key_id,json=signedPreKeyId,proto3" json:"signed_pre_key_id,omitempty"`
	BaseKey        []byte                 `protobuf:"bytes,2,opt,name=base_key,json=baseKey,proto3" json:"base_key,omitempty"`
	Timestamp      uint64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SessionStructure_PendingPreKey) Reset() {
	*x = SessionStructure_PendingPreKey{}
	mi := &file_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStructure_PendingPreKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStructure_PendingPreKey) ProtoMessage() {}

func (x *SessionStructure_PendingPreKey) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStructure_PendingPreKey.ProtoReflect.Descriptor instead.
func (*SessionStructure_PendingPreKey) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0, 1}
}

func (x *SessionStructure_PendingPreKey) GetPreKeyId() uint32 {
	if x != nil && x.PreKeyId != nil {
		return *x.PreKeyId
	}
	return 0
}

func (x *SessionStructure_PendingPreKey) GetSignedPreKeyId() int32 {
	if x != nil {
		return x.SignedPreKeyId
	}
	return 0
}

func (x *SessionStructure_PendingPreKey) GetBaseKey() []byte {
	if x != nil {
		return x.BaseKey
	}
	return nil
}

func (x *SessionStructure_PendingPreKey) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SessionStructure_PendingKyberPreKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PreKeyId      uint32                 `protobuf:"varint,1,opt,name=pre_key_id,json=preKeyId,proto3" json:"pre_key_id,omitempty"`
	Ciphertext    []byte                 `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStructure_PendingKyberPreKey) Reset() {
	*x = SessionStructure_PendingKyberPreKey{}
	mi := &file_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStructure_PendingKyberPreKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStructure_PendingKyberPreKey) ProtoMessage() {}

func (x *SessionStructure_PendingKyberPreKey) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStructure_PendingKyberPreKey.ProtoReflect.Descriptor instead.
func (*SessionStructure_PendingKyberPreKey) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0, 2}
}

func (x *SessionStructure_PendingKyberPreKey) GetPreKeyId() uint32 {
	if x != nil {
		return x.PreKeyId
	}
	return 0
}

func (x *SessionStructure_PendingKyberPreKey) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

type SessionStructure_Chain_ChainKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStructure_Chain_ChainKey) Reset() {
	*x = SessionStructure_Chain_ChainKey{}
	mi := &file_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStructure_Chain_ChainKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStructure_Chain_ChainKey) ProtoMessage() {}

func (x *SessionStructure_Chain_ChainKey) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStructure_Chain_ChainKey.ProtoReflect.Descriptor instead.
func (*SessionStructure_Chain_ChainKey) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *SessionStructure_Chain_ChainKey) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SessionStructure_Chain_ChainKey) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type SessionStructure_Chain_MessageKey struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Index     uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	CipherKey []byte                 `protobuf:"bytes,2,opt,name=cipher_key,json=cipherKey,proto3" json:"cipher_key,omitempty"`
	MacKey    []byte                 `protobuf:"bytes,3,opt,name=mac_key,json=macKey,proto3" json:"mac_key,omitempty"`
	Iv        []byte                 `protobuf:"bytes,4,opt,name=iv,proto3" json:"iv,omitempty"`
	// If `seed` is set, then `cipher_key`, `mac_key`, and `iv`
	// will be empty and should be generated from it.
	Seed          []byte `protobuf:"bytes,5,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStructure_Chain_MessageKey) Reset() {
	*x = SessionStructure_Chain_MessageKey{}
	mi := &file_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStructure_Chain_MessageKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStructure_Chain_MessageKey) ProtoMessage() {}

func (x *SessionStructure_Chain_MessageKey) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStructure_Chain_MessageKey.ProtoReflect.Descriptor instead.
func (*SessionStructure_Chain_MessageKey) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *SessionStructure_Chain_MessageKey) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SessionStructure_Chain_MessageKey) GetCipherKey() []byte {
	if x != nil {
		return x.CipherKey
	}
	return nil
}

func (x *SessionStructure_Chain_MessageKey) GetMacKey() []byte {
	if x != nil {
		return x.MacKey
	}
	return nil
}

func (x *SessionStructure_Chain_MessageKey) GetIv() []byte {
	if x != nil {
		return x.Iv
	}
	return nil
}

func (x *SessionStructure_Chain_MessageKey) GetSeed() []byte {
	if x != nil {
		return x.Seed
	}
	return nil
}

type SenderKeyStateStructure_SenderChainKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Iteration     uint32                 `protobuf:"varint,1,opt,name=iteration,proto3" json:"iteration,omitempty"`
	Seed          []byte                 `protobuf:"bytes,2,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SenderKeyStateStructure_SenderChainKey) Reset() {
	*x = SenderKeyStateStructure_SenderChainKey{}
	mi := &file_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SenderKeyStateStructure_SenderChainKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderKeyStateStructure_SenderChainKey) ProtoMessage() {}

func (x *SenderKeyStateStructure_SenderChainKey) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderKeyStateStructure_SenderChainKey.ProtoReflect.Descriptor instead.
func (*SenderKeyStateStructure_SenderChainKey) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{5, 0}
}

func (x *SenderKeyStateStructure_SenderChainKey) GetIteration() uint32 {
	if x != nil {
		return x.Iteration
	}
	return 0
}

func (x *SenderKeyStateStructure_SenderChainKey) GetSeed() []byte {
	if x != nil {
		return x.Seed
	}
	return nil
}

type SenderKeyStateStructure_SenderMessageKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Iteration     uint32                 `protobuf:"varint,1,opt,name=iteration,proto3" json:"iteration,omitempty"`
	Seed          []byte                 `protobuf:"bytes,2,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SenderKeyStateStructure_SenderMessageKey) Reset() {
	*x = SenderKeyStateStructure_SenderMessageKey{}
	mi := &file_storage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SenderKeyStateStructure_SenderMessageKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderKeyStateStructure_SenderMessageKey) ProtoMessage() {}

func (x *SenderKeyStateStructure_SenderMessageKey) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderKeyStateStructure_SenderMessageKey.ProtoReflect.Descriptor instead.
func (*SenderKeyStateStructure_SenderMessageKey) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{5, 1}
}

func (x *SenderKeyStateStructure_SenderMessageKey) GetIteration() uint32 {
	if x != nil {
		return x.Iteration
	}
	return 0
}

func (x *SenderKeyStateStructure_SenderMessageKey) GetSeed() []byte {
	if x != nil {
		return x.Seed
	}
	return nil
}

type SenderKeyStateStructure_SenderSigningKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Public        []byte                 `protobuf:"bytes,1,opt,name=public,proto3" json:"public,omitempty"`
	Private       []byte                 `protobuf:"bytes,2,opt,name=private,proto3" json:"private,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SenderKeyStateStructure_SenderSigningKey) Reset() {
	*x = SenderKeyStateStructure_SenderSigningKey{}
	mi := &file_storage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SenderKeyStateStructure_SenderSigningKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderKeyStateStructure_SenderSigningKey) ProtoMessage() {}

func (x *SenderKeyStateStructure_SenderSigningKey) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderKeyStateStructure_SenderSigningKey.ProtoReflect.Descriptor instead.
func (*SenderKeyStateStructure_SenderSigningKey) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{5, 2}
}

func (x *SenderKeyStateStructure_SenderSigningKey) GetPublic() []byte {
	if x != nil {
		return x.Public
	}
	return nil
}

func (x *SenderKeyStateStructure_SenderSigningKey) GetPrivate() []byte {
	if x != nil {
		return x.Private
	}
	return nil
}

var File_storage_proto protoreflect.FileDescriptor

const file_storage_proto_rawDesc = "" +
	"\n" +
	"\rstorage.proto\x12\x14signal.proto.storage\"\xf4\v\n" +
	"\x10SessionStructure\x12'\n" +
	"\x0fsession_version\x18\x01 \x01(\rR\x0esessionVersion\x122\n" +
	"\x15local_identity_public\x18\x02 \x01(\fR\x13localIdentityPublic\x124\n" +
	"\x16remote_identity_public\x18\x03 \x01(\fR\x14remoteIdentityPublic\x12\x19\n" +
	"\broot_key\x18\x04 \x01(\fR\arootKey\x12)\n" +
	"\x10previous_counter\x18\x05 \x01(\rR\x0fpreviousCounter\x12O\n" +
	"\fsender_chain\x18\x06 \x01(\v2,.signal.proto.storage.SessionStructure.ChainR\vsenderChain\x12U\n" +
	"\x0freceiver_chains\x18\a \x03(\v2,.signal.proto.storage.SessionStructure.ChainR\x0ereceiverChains\x12\\\n" +
	"\x0fpending_pre_key\x18\t \x01(\v24.signal.proto.storage.SessionStructure.PendingPreKeyR\rpendingPreKey\x12l\n" +
	"\x15pending_kyber_pre_key\x18\x0e \x01(\v29.signal.proto.storage.SessionStructure.PendingKyberPreKeyR\x12pendingKyberPreKey\x124\n" +
	"\x16remote_registration_id\x18\n" +
	" \x01(\rR\x14remoteRegistrationId\x122\n" +
	"\x15local_registration_id\x18\v \x01(\rR\x13localRegistrationId\x12$\n" +
	"\x0ealice_base_key\x18\r \x01(\fR\faliceBaseKey\x12(\n" +
	"\x10pq_ratchet_state\x18\x0f \x01(\fR\x0epqRatchetState\x1a\xd6\x03\n" +
	"\x05Chain\x12,\n" +
	"\x12sender_ratchet_key\x18\x01 \x01(\fR\x10senderRatchetKey\x12;\n" +
	"\x1asender_ratchet_key_private\x18\x02 \x01(\fR\x17senderRatchetKeyPrivate\x12R\n" +
	"\tchain_key\x18\x03 \x01(\v25.signal.proto.storage.SessionStructure.Chain.ChainKeyR\bchainKey\x12Z\n" +
	"\fmessage_keys\x18\x04 \x03(\v27.signal.proto.storage.SessionStructure.Chain.MessageKeyR\vmessageKeys\x1a2\n" +
	"\bChainKey\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x1a~\n" +
	"\n" +
	"MessageKey\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x1d\n" +
	"\n" +
	"cipher_key\x18\x02 \x01(\fR\tcipherKey\x12\x17\n" +
	"\amac_key\x18\x03 \x01(\fR\x06macKey\x12\x0e\n" +
	"\x02iv\x18\x04 \x01(\fR\x02iv\x12\x12\n" +
	"\x04seed\x18\x05 \x01(\fR\x04seed\x1a\xa5\x01\n" +
	"\rPendingPreKey\x12!\n" +
	"\n" +
	"pre_key_id\x18\x01 \x01(\rH\x00R\bpreKeyId\x88\x01\x01\x12)\n" +
	"\x11signed_pre_key_id\x18\x03 \x01(\x05R\x0esignedPreKeyId\x12\x19\n" +
	"\bbase_key\x18\x02 \x01(\fR\abaseKey\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestampB\r\n" +
	"\v_pre_key_id\x1aR\n" +
	"\x12PendingKyberPreKey\x12\x1c\n" +
	"\n" +
	"pre_key_id\x18\x01 \x01(\rR\bpreKeyId\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x02 \x01(\fR\n" +
	"ciphertextJ\x04\b\f\x10\r\"\x8f\x01\n" +
	"\x0fRecordStructure\x12O\n" +
	"\x0fcurrent_session\x18\x01 \x01(\v2&.signal.proto.storage.SessionStructureR\x0ecurrentSession\x12+\n" +
	"\x11previous_sessions\x18\x02 \x03(\fR\x10previousSessions\"g\n" +
	"\x15PreKeyRecordStructure\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12\x1f\n" +
	"\vprivate_key\x18\x03 \x01(\fR\n" +
	"privateKey\"\xa9\x01\n" +
	"\x1bSignedPreKeyRecordStructure\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12\x1f\n" +
	"\vprivate_key\x18\x03 \x01(\fR\n" +
	"privateKey\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x06R\ttimestamp\"Z\n" +
	"\x18IdentityKeyPairStructure\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x1f\n" +
	"\vprivate_key\x18\x02 \x01(\fR\n" +
	"privateKey\"\xf3\x04\n" +
	"\x17SenderKeyStateStructure\x12'\n" +
	"\x0fmessage_version\x18\x05 \x01(\rR\x0emessageVersion\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\rR\achainId\x12f\n" +
	"\x10sender_chain_key\x18\x02 \x01(\v2<.signal.proto.storage.SenderKeyStateStructure.SenderChainKeyR\x0esenderChainKey\x12l\n" +
	"\x12sender_signing_key\x18\x03 \x01(\v2>.signal.proto.storage.SenderKeyStateStructure.SenderSigningKeyR\x10senderSigningKey\x12n\n" +
	"\x13sender_message_keys\x18\x04 \x03(\v2>.signal.proto.storage.SenderKeyStateStructure.SenderMessageKeyR\x11senderMessageKeys\x1aB\n" +
	"\x0eSenderChainKey\x12\x1c\n" +
	"\titeration\x18\x01 \x01(\rR\titeration\x12\x12\n" +
	"\x04seed\x18\x02 \x01(\fR\x04seed\x1aD\n" +
	"\x10SenderMessageKey\x12\x1c\n" +
	"\titeration\x18\x01 \x01(\rR\titeration\x12\x12\n" +
	"\x04seed\x18\x02 \x01(\fR\x04seed\x1aD\n" +
	"\x10SenderSigningKey\x12\x16\n" +
	"\x06public\x18\x01 \x01(\fR\x06public\x12\x18\n" +
	"\aprivate\x18\x02 \x01(\fR\aprivate\"u\n" +
	"\x18SenderKeyRecordStructure\x12Y\n" +
	"\x11sender_key_states\x18\x01 \x03(\v2-.signal.proto.storage.SenderKeyStateStructureR\x0fsenderKeyStatesB+Z)github.com/GoCodeAlone/libsignal-go/protob\x06proto3"

var (
	file_storage_proto_rawDescOnce sync.Once
	file_storage_proto_rawDescData []byte
)

func file_storage_proto_rawDescGZIP() []byte {
	file_storage_proto_rawDescOnce.Do(func() {
		file_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)))
	})
	return file_storage_proto_rawDescData
}

var file_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_storage_proto_goTypes = []any{
	(*SessionStructure)(nil),                         // 0: signal.proto.storage.SessionStructure
	(*RecordStructure)(nil),                          // 1: signal.proto.storage.RecordStructure
	(*PreKeyRecordStructure)(nil),                    // 2: signal.proto.storage.PreKeyRecordStructure
	(*SignedPreKeyRecordStructure)(nil),              // 3: signal.proto.storage.SignedPreKeyRecordStructure
	(*IdentityKeyPairStructure)(nil),                 // 4: signal.proto.storage.IdentityKeyPairStructure
	(*SenderKeyStateStructure)(nil),                  // 5: signal.proto.storage.SenderKeyStateStructure
	(*SenderKeyRecordStructure)(nil),                 // 6: signal.proto.storage.SenderKeyRecordStructure
	(*SessionStructure_Chain)(nil),                   // 7: signal.proto.storage.SessionStructure.Chain
	(*SessionStructure_PendingPreKey)(nil),           // 8: signal.proto.storage.SessionStructure.PendingPreKey
	(*SessionStructure_PendingKyberPreKey)(nil),      // 9: signal.proto.storage.SessionStructure.PendingKyberPreKey
	(*SessionStructure_Chain_ChainKey)(nil),          // 10: signal.proto.storage.SessionStructure.Chain.ChainKey
	(*SessionStructure_Chain_MessageKey)(nil),        // 11: signal.proto.storage.SessionStructure.Chain.MessageKey
	(*SenderKeyStateStructure_SenderChainKey)(nil),   // 12: signal.proto.storage.SenderKeyStateStructure.SenderChainKey
	(*SenderKeyStateStructure_SenderMessageKey)(nil), // 13: signal.proto.storage.SenderKeyStateStructure.SenderMessageKey
	(*SenderKeyStateStructure_SenderSigningKey)(nil), // 14: signal.proto.storage.SenderKeyStateStructure.SenderSigningKey
}
var file_storage_proto_depIdxs = []int32{
	7,  // 0: signal.proto.storage.SessionStructure.sender_chain:type_name -> signal.proto.storage.SessionStructure.Chain
	7,  // 1: signal.proto.storage.SessionStructure.receiver_chains:type_name -> signal.proto.storage.SessionStructure.Chain
	8,  // 2: signal.proto.storage.SessionStructure.pending_pre_key:type_name -> signal.proto.storage.SessionStructure.PendingPreKey
	9,  // 3: signal.proto.storage.SessionStructure.pending_kyber_pre_key:type_name -> signal.proto.storage.SessionStructure.PendingKyberPreKey
	0,  // 4: signal.proto.storage.RecordStructure.current_session:type_name -> signal.proto.storage.SessionStructure
	12, // 5: signal.proto.storage.SenderKeyStateStructure.sender_chain_key:type_name -> signal.proto.storage.SenderKeyStateStructure.SenderChainKey
	14, // 6: signal.proto.storage.SenderKeyStateStructure.sender_signing_key:type_name -> signal.proto.storage.SenderKeyStateStructure.SenderSigningKey
	13, // 7: signal.proto.storage.SenderKeyStateStructure.sender_message_keys:type_name -> signal.proto.storage.SenderKeyStateStructure.SenderMessageKey
	5,  // 8: signal.proto.storage.SenderKeyRecordStructure.sender_key_states:type_name -> signal.proto.storage.SenderKeyStateStructure
	10, // 9: signal.proto.storage.SessionStructure.Chain.chain_key:type_name -> signal.proto.storage.SessionStructure.Chain.ChainKey
	11, // 10: signal.proto.storage.SessionStructure.Chain.message_keys:type_name -> signal.proto.storage.SessionStructure.Chain.MessageKey
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_storage_proto_init() }
func file_storage_proto_init() {
	if File_storage_proto != nil {
		return
	}
	file_storage_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storage_proto_goTypes,
		DependencyIndexes: file_storage_proto_depIdxs,
		MessageInfos:      file_storage_proto_msgTypes,
	}.Build()
	File_storage_proto = out.File
	file_storage_proto_goTypes = nil
	file_storage_proto_depIdxs = nil
}
