// Copyright 2026 Signal Messenger, LLC.
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/accountkeysproto/mfa_metadata.proto

package accountkeysproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MfaKeyMetadataPlaintext struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	CreationEpochTimeSeconds uint64                 `protobuf:"varint,1,opt,name=creation_epoch_time_seconds,json=creationEpochTimeSeconds,proto3" json:"creation_epoch_time_seconds,omitempty"`
	KeyName                  string                 `protobuf:"bytes,2,opt,name=key_name,json=keyName,proto3" json:"key_name,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *MfaKeyMetadataPlaintext) Reset() {
	*x = MfaKeyMetadataPlaintext{}
	mi := &file_internal_accountkeysproto_mfa_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MfaKeyMetadataPlaintext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MfaKeyMetadataPlaintext) ProtoMessage() {}

func (x *MfaKeyMetadataPlaintext) ProtoReflect() protoreflect.Message {
	mi := &file_internal_accountkeysproto_mfa_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MfaKeyMetadataPlaintext.ProtoReflect.Descriptor instead.
func (*MfaKeyMetadataPlaintext) Descriptor() ([]byte, []int) {
	return file_internal_accountkeysproto_mfa_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *MfaKeyMetadataPlaintext) GetCreationEpochTimeSeconds() uint64 {
	if x != nil {
		return x.CreationEpochTimeSeconds
	}
	return 0
}

func (x *MfaKeyMetadataPlaintext) GetKeyName() string {
	if x != nil {
		return x.KeyName
	}
	return ""
}

var File_internal_accountkeysproto_mfa_metadata_proto protoreflect.FileDescriptor

const file_internal_accountkeysproto_mfa_metadata_proto_rawDesc = "" +
	"\n" +
	",internal/accountkeysproto/mfa_metadata.proto\x12 signal.account_keys.mfa_metadata\"s\n" +
	"\x17MfaKeyMetadataPlaintext\x12=\n" +
	"\x1bcreation_epoch_time_seconds\x18\x01 \x01(\x04R\x18creationEpochTimeSeconds\x12\x19\n" +
	"\bkey_name\x18\x02 \x01(\tR\akeyNameB?Z=github.com/GoCodeAlone/libsignal-go/internal/accountkeysprotob\x06proto3"

var (
	file_internal_accountkeysproto_mfa_metadata_proto_rawDescOnce sync.Once
	file_internal_accountkeysproto_mfa_metadata_proto_rawDescData []byte
)

func file_internal_accountkeysproto_mfa_metadata_proto_rawDescGZIP() []byte {
	file_internal_accountkeysproto_mfa_metadata_proto_rawDescOnce.Do(func() {
		file_internal_accountkeysproto_mfa_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_accountkeysproto_mfa_metadata_proto_rawDesc), len(file_internal_accountkeysproto_mfa_metadata_proto_rawDesc)))
	})
	return file_internal_accountkeysproto_mfa_metadata_proto_rawDescData
}

var file_internal_accountkeysproto_mfa_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_accountkeysproto_mfa_metadata_proto_goTypes = []any{
	(*MfaKeyMetadataPlaintext)(nil), // 0: signal.account_keys.mfa_metadata.MfaKeyMetadataPlaintext
}
var file_internal_accountkeysproto_mfa_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_accountkeysproto_mfa_metadata_proto_init() }
func file_internal_accountkeysproto_mfa_metadata_proto_init() {
	if File_internal_accountkeysproto_mfa_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_accountkeysproto_mfa_metadata_proto_rawDesc), len(file_internal_accountkeysproto_mfa_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_accountkeysproto_mfa_metadata_proto_goTypes,
		DependencyIndexes: file_internal_accountkeysproto_mfa_metadata_proto_depIdxs,
		MessageInfos:      file_internal_accountkeysproto_mfa_metadata_proto_msgTypes,
	}.Build()
	File_internal_accountkeysproto_mfa_metadata_proto = out.File
	file_internal_accountkeysproto_mfa_metadata_proto_goTypes = nil
	file_internal_accountkeysproto_mfa_metadata_proto_depIdxs = nil
}
